Update dotnet-watch.md
dotnet/AspNetCore.Docs pull request #19815
Opened 2020-09-09 22:02 UTC by pranavkm

2020-09-11 23:10 UTC, DamianEdwards requested changes

2020-09-11 23:28 UTC, Rick-Anderson commented
@pranavkm  hold off commits, I'm working on this.

2020-09-11 23:36 UTC, pranavkm reviewed
🖖

2020-09-11 23:36 UTC, pranavkm commented on aspnetcore/tutorials/dotnet-watch.md
>  In addition to this, `dotnet watch` can also refresh the browser when it detects changes to watched files. To do this, watch command injects a middleware to the app that modifies HTML responses creat
```suggestion
In addition to this, `dotnet watch` can also refresh the browser when it detects changes to watched files. To do this, watch command injects a middleware to the app that modifies HTML responses created by the app. The middleware adds a JavaScript script block to the page that allows `dotnet watch` to instruct the browser to refresh. Currently changes to all watched files, including static content such as .html and .css files will cause the app to be rebuilt.

```

2020-09-14 20:37 UTC, Rick-Anderson commented
@pranavkm  I think my commit addressed all the issues, if not, can you fix them. Let me know when I can merge this.

2020-09-14 20:37 UTC, Rick-Anderson approved these changes

2020-09-14 22:43 UTC, pranavkm commented
Let's get this in!

2020-09-14 22:45 UTC, merged