Add notes about behavior changes to model binding in 5.0
dotnet/AspNetCore.Docs pull request #19971
Opened 2020-09-22 23:50 UTC by pranavkm

2020-09-22 23:52 UTC, pranavkm commented on aspnetcore/migration/31-to-50.md
> +## Changes to model binding in ASP.NET Core MVC and Razor Pages
I don't think these qualify as breaking changes but it is useful to document these in some place and point users to if they ask.

2020-09-22 23:55 UTC, Rick-Anderson approved these changes

2020-09-22 23:58 UTC, Rick-Anderson commented
@pranavkm  see my commit for slight tweaks.

2020-09-22 23:59 UTC, pranavkm reviewed
:shipit:

2020-09-23 01:53 UTC, scottaddie requested changes

2020-09-23 01:53 UTC, scottaddie commented on aspnetcore/migration/31-to-50.md
> +In previous versions, `DateTime` values were model bound as local time where the timezone was determined by the server. DateTime values bound from input formatting (JSON), and `DateTimeOffset` values
```suggestion
In ASP.NET Core 3.1 and earlier, `DateTime` values were model bound as local time where the timezone was determined by the server. `DateTime` values bound from input formatting (JSON) and `DateTimeOffset` values were bound as UTC timezones. In ASP.NET Core 5.0 and later, model binding consistently binds `DateTime` values with the UTC timezone.
```

2020-09-23 01:53 UTC, scottaddie commented on aspnetcore/migration/31-to-50.md
> +```C#
```suggestion
```csharp
```

2020-09-24 01:24 UTC, merged