Update intro.md
dotnet/AspNetCore.Docs pull request #20880
Opened 2020-12-07 01:17 UTC by the-wazz

Added a missing step (and some text) to the 'Add Razor Pages using Entity Framework (CRUD)' dialog:

2020-12-09 18:40 UTC, scottaddie requested changes
Thank you for the PR. Here are some minor changes to incorporate.

2020-12-09 18:40 UTC, scottaddie commented on aspnetcore/data/ef-rp/intro.md
> +   * Select **Add** to finish the 'Add Razor Pages' dialog.
```suggestion
    * Select **Add** to finish adding the data context class.
   * Select **Add** to finish the **Add Razor Pages** dialog.
```

2020-12-10 02:11 UTC, the-wazz commented
@Rick-Anderson @scottaddie My first time incorporating someone else's changes. Let me know if I did it wrong or there's something else to do.

2020-12-10 19:24 UTC, scottaddie approved these changes

2020-12-10 19:24 UTC, merged

2020-12-10 19:24 UTC, scottaddie commented
@the-wazz You did great! Thank you for fixing this issue in the doc.