Remove BundlerMinifier in bundling-and-minification-md
dotnet/AspNetCore.Docs pull request #21770
Opened 2021-03-12 19:11 UTC by wadepickett

Early draft, some collaboration work to do.

2021-03-12 21:26 UTC, scottaddie requested changes
In addition to the suggestions below, please remove the **Consume bundleconfig.json from Gulp** section.

2021-03-12 21:26 UTC, scottaddie commented on aspnetcore/client-side/bundling-and-minification.md
> +The MVC and Razor Pages project templates provide a configuration solution for bundling and minification workflow consisting of a JSON configuration file. Third-party tools, such as the [Grunt](xref:
Remove this **Configure bundling and minification** section, as it's based on _bundleconfig.json_. That JSON file existed to support Mads' VS extension.

2021-03-12 21:26 UTC, scottaddie commented on aspnetcore/client-side/bundling-and-minification.md
>  ## Add files to workflow
This section should be removed too, since it's based on _bundleconfig.json_.

2021-03-12 22:36 UTC, scottaddie commented
As part of this PR, I suggest we also retire https://docs.microsoft.com/aspnet/core/client-side/using-grunt. Grunt is an open-source tool that Microsoft doesn't own, and this doc is seriously outdated. Grunt was used for bundling & minification is the very early days of ASP.NET Core (in the days of DNX and _project.json_). It too was removed from the project templates. After retiring the doc, you can redirect to https://gruntjs.com.

2021-03-15 17:49 UTC, wadepickett commented
@scottaddie, I will remove using-grunt.md as a 2nd pr today since an number of topics reference it, and this needs to be published right away.

2021-03-15 18:02 UTC, wadepickett commented
@scottaddie, The gulpfile.js example we specify `bundleconfig = require('./bundleconfig.json');`     The json could be named anything in this case, and it makes sense to call your own bundleconfig.json, but that might also cause some confusion since the template used to provide that.  I'm thinking we should just leave it named thus however.

2021-03-15 18:13 UTC, scottaddie commented
@wadepickett Let's remove that entire **Consume bundleconfig.json from Gulp** section. The VS extension provided an option to right-click the *bundleconfig.json* file and convert it to *gulpfile.js*. We don't want to lead anyone to believe that's still supported.

2021-03-15 18:26 UTC, wadepickett commented
@scottaddie, per our discussion I will remove the sample folder plus these sections in moment.
•	Consume bundleconfig.json from Gulp
•	Run Gulp tasks

2021-03-15 18:56 UTC, wadepickett commented
@madskristensen, for visibility, review.

2021-03-15 19:01 UTC, scottaddie requested changes
See my suggestions below. Also, I recommend removing the **Use Grunt** link from the **Additional resources** section. Grunt was used in the project templates only in the very early days of ASP.NET Core. It was later replaced with Gulp.

2021-03-15 19:01 UTC, scottaddie commented on aspnetcore/client-side/bundling-and-minification.md
> +Third-party tools, such as the [Grunt](https://gruntjs.com) task runner, provide a workflow solution for bundling and minification, as well as linting and image optimization. By using design-time bun
```suggestion
Third-party tools, such as [Gulp](https://gulpjs.com) and [Webpack](https://webpack.js.org), provide workflow automation for bundling and minification, as well as linting and image optimization. By using design-time bundling and minification, the minified files are created prior to the app's deployment. Bundling and minifying before deployment provides the advantage of reduced server load. However, it's important to recognize that design-time bundling and minification increases build complexity and only works with static files.
```

2021-03-15 20:08 UTC, madskristensen commented
LGTM

2021-03-15 20:09 UTC, wadepickett commented
Updates per review all in, however OPS services are not available as of a few minutes ago, so I can't get a doc validation and build until that is fixed.  I'm watching for it...

2021-03-15 20:36 UTC, scottaddie commented
@wadepickett The doc build failure is likely related to the current Azure AD outage. Try retriggering the build once that outage is resolved.

2021-03-15 20:44 UTC, scottaddie approved these changes

2021-03-15 21:39 UTC, merged