Updated documentation to include PersistKeysToDbContext
dotnet/AspNetCore.Docs pull request #22003
Opened 2021-04-08 10:50 UTC by markmcgookin

Fixes #21996

Updated documentation to cover for PersistKeysToDbContext functionality in aspnetcore > security > data-protection > configuration > overview

2021-04-16 01:19 UTC, Rick-Anderson requested changes
Suggested edits to conform to style guide.

2021-04-16 01:19 UTC, Rick-Anderson commented on aspnetcore/security/data-protection/configuration/overview.md
> +This will store the keys used in the configured database. The database context being used must adhere to `IDataProtectionKeyContext` which exposes the property `DataProtectionKeys`
```suggestion
The preceding code stores the keys in the configured database. The database context being used must implement `IDataProtectionKeyContext`.  `IDataProtectionKeyContext` exposes the property `DataProtectionKeys` 
```

2021-04-16 01:19 UTC, Rick-Anderson commented on aspnetcore/security/data-protection/configuration/overview.md
> +This property represents the table in which the keys will be stored. The definition of this type [can be found here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.dataprotection.en
```suggestion
This property represents the table in which the keys are stored. Create the table manually or with `DbContext` Migrations. See <xref:Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey> for more information.
```

2021-05-02 13:23 UTC, markmcgookin commented
I've applied the edits suggested a few weeks ago. Do we need to do anything more on this or can it get merged in? (and we can close off the issue it addresses as well)

2021-05-02 14:07 UTC, blowdart approved these changes

2021-05-02 16:43 UTC, Rick-Anderson commented
Sorry @markmcgookin  I didn't notice. Next time let me know by requesting a re-review
![image](https://user-images.githubusercontent.com/3605364/116820592-9bb42400-ab11-11eb-8d0d-413de7041177.png)

S&M automatically closes the issue.

2021-05-02 16:43 UTC, merged

2021-05-02 17:21 UTC, markmcgookin commented
Ah sorry man, I didn’t realise. Thanks!

Sent from my iPhone

> On 2 May 2021, at 17:43, Rick Anderson ***@***.***> wrote:
> 
> ﻿
> Sorry @markmcgookin I didn't notice. Next time let me know by requesting a re-review
> 
> 
> S&M automatically closes the issue.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.