Update ui-class.md
dotnet/AspNetCore.Docs pull request #22808
Opened 2021-07-22 09:26 UTC by fiyazbinhasan

Fixes https://github.com/dotnet/AspNetCore.Docs/issues/20788

@Rick-Anderson, please review

2021-07-22 14:28 UTC, Rick-Anderson requested changes

2021-07-22 14:28 UTC, Rick-Anderson commented on aspnetcore/razor-pages/ui-class/samples/Startup.cs
> +```csharp
Make a complete startup file

2021-07-22 14:28 UTC, Rick-Anderson commented on aspnetcore/razor-pages/ui-class.md
> +```csharp
Finish moving this to file. Use snippet syntax to highlight the two lies
Example syntax
`[!code-csharp[](start-mvc/sample/src/MvcMovie/Models/MovieDateFormat.cs?name=snippet1&highlight=2,10)]`

2021-07-23 14:01 UTC, Rick-Anderson commented on aspnetcore/razor-pages/ui-class.md
> +One must enable `Razor Pages` in the web app to make sure the page based routing works. For example, in an MVC application, register the `Razor Pages` services and map the pages with endpoint routing
```suggestion
If Razor Pages are used in the RCL, Razor Pages services and endpoints must be enabled in the hosting app:
```

2021-07-23 14:02 UTC, Rick-Anderson commented
@serpent5  please review

2021-07-23 19:53 UTC, serpent5 approved these changes
Just a minor suggestion to switch from a passive to an active voice.

Nice work @fiyazbinhasan. ⭐

2021-07-23 19:53 UTC, serpent5 commented on aspnetcore/razor-pages/ui-class.md
> +If Razor Pages are used in the RCL, Razor Pages services and endpoints must be enabled in the hosting app:
```suggestion
If the RCL uses Razor Pages, enable the Razor Pages services and endpoints in the hosting app:
```

2021-07-23 19:58 UTC, Rick-Anderson approved these changes

2021-07-23 20:16 UTC, fiyazbinhasan commented
thanks @serpent5 😃

2021-07-23 20:39 UTC, merged

2021-08-01 01:21 UTC, chengyanbing commented
When I build it, it shows: ...aspnetcore\razor-pages\ui-class\samples\cli\WebApp1\Pages\Error.cshtml.cs(17,10,17,92): warning MVC1001: 'ResponseCacheAttribute' cannot be applied to Razor Page handler methods. It may be applied either to the Razor Page model or applied globally.

2021-08-01 17:06 UTC, fiyazbinhasan commented
Nice catch. I'll add a fix for that. @chengyanbing