Choose Web UI Links
dotnet/AspNetCore.Docs pull request #22968
Opened 2021-08-06 23:21 UTC by wadepickett

Creating an include that links to the Choose Web UI topic.  This will be included at the top level of getting started tutorials.

2021-08-09 23:51 UTC, wadepickett commented
@Rick-Anderson,  embarrassingly, I'm not understanding why I am getting a build fail here.  Do you see what I might be doing wrong?  The warnings are the usual alt text duplication warnings we get on multi-version docs like these.   The include shows up in the topics fine however as intended in the build.  Do I ignore the build fail or is there something I am missing that I can fix here?  Although it would be odd, it occurred to me that new include files might need to be published first before referencing them, even though they show up in the build, is that it?

Also, you wanted a link in the Blazor getting started, but the one we point to for getting started is on the Marketing/new customer site, not in docs, and not in this repo.  As an alternative, It doesn't feel right to mention this link in the to do list Blazor tutorial, which we do not promote as a starting point.  Thoughts?

2021-08-10 07:59 UTC, wadepickett commented
@Rick-Anderson, please disregard my question about the build fail. We have repeating alt text warning for just about any of the multi-version topics but I don't remember the build failing over them, so I though I must have an issue with the way I did the include.  It is my first new include.  I guess it really is just the alt text issues.

Also, I tried to model (copy) after one of the existing includes, but I see those were not following the latest expected for metadata, so fixing that.

2021-08-10 20:42 UTC, Rick-Anderson requested changes

2021-08-10 20:42 UTC, Rick-Anderson commented on aspnetcore/tutorials/first-mvc-app/start-mvc.md
>  [!INCLUDE [consider RP](~/includes/razor.md)]
Update this include
`
This tutorial teaches ASP.NET Core MVC web development with controllers and views. If you're new to ASP.NET Core web development, consider the [Razor Pages](xref:tutorials/razor-pages/razor-pages-start) version of this tutorial, which provides an easier starting point. See [choose UI ...](_) which compares ... `

2021-08-10 20:42 UTC, Rick-Anderson commented on aspnetcore/tutorials/first-mvc-app/start-mvc.md
> +[!INCLUDE [Choose web UI](~/includes/choose-ui-link.md)]
```suggestion
```

2021-08-10 23:24 UTC, wadepickett commented
close / reopen to force build.

2021-08-10 23:48 UTC, Rick-Anderson commented
@wadepickett  once you get this error you can't eliminate it from close/open. It's a bogus error see #22992

2021-08-10 23:49 UTC, Rick-Anderson requested changes

2021-08-10 23:49 UTC, Rick-Anderson commented on aspnetcore/includes/razor.md
> +This tutorial teaches ASP.NET Core MVC web development with controllers and views. If you're new to ASP.NET Core web development, consider the [Razor Pages](xref:tutorials/razor-pages/razor-pages-sta
```suggestion
This tutorial teaches ASP.NET Core MVC web development with controllers and views. If you're new to ASP.NET Core web development, consider the [Razor Pages](xref:tutorials/razor-pages/razor-pages-start) version of this tutorial, which provides an easier starting point. See <xref:tutorials/choose-web-ui>, which compares Razor Pages, MVC, and Blazor for UI development..
```

2021-08-11 19:58 UTC, Rick-Anderson approved these changes

2021-08-11 19:59 UTC, Rick-Anderson commented
@wadepickett  double check those warnings

2021-08-11 20:00 UTC, Rick-Anderson requested changes
Some of those look like legitimate duplicates, not caused by monikers.

2021-08-12 14:01 UTC, merged