Update http3.md
dotnet/AspNetCore.Docs pull request #23001
Opened 2021-08-11 18:33 UTC by samsp-msft

Fixed a typo and added a bit more context.

2021-08-11 19:53 UTC, Rick-Anderson requested changes

2021-08-11 19:53 UTC, Rick-Anderson commented on aspnetcore/fundamentals/servers/kestrel/http3.md
> +As HTTP/3 support is in preview, it is not enabled by default.
```suggestion
HTTP/3 support is in preview, therefore it's not enabled by default.
```

2021-08-11 19:53 UTC, Rick-Anderson commented on aspnetcore/fundamentals/servers/kestrel/http3.md
> +HTTP/3 uses QUIC as its transport protocol. The .NET implementation of HTTP/3 uses [MsQuic](https://github.com/microsoft/msquic) to provide QUIC functionality. MSQuic is included in specific builds o
```suggestion
HTTP/3 uses QUIC as its transport protocol. The .NET implementation of HTTP/3 uses [MsQuic](https://github.com/microsoft/msquic) to provide QUIC functionality. MSQuic is included in specific builds of windows and as a library for Linux. If the platform that Kestrel is running on doesn't have all the requirements for HTTP/3 then it's disabled.
```

2021-08-12 14:21 UTC, Rick-Anderson commented
@samsp-msft  can you accept/reject my suggestions or give me permission to apply them?

2021-08-12 17:31 UTC, samsp-msft commented
Applied your suggestions. The checkbox for allowing edits by maintainers is checked, do I need to do something else to give you permissions?

2021-08-12 17:57 UTC, Rick-Anderson commented
> Applied your suggestions. The checkbox for allowing edits by maintainers is checked, do I need to do something else to give you permissions?

Nope, I just didn't want to apply them without your permission. Thanks

2021-08-12 18:15 UTC, merged

2021-08-12 18:16 UTC, Rick-Anderson commented
@samsp-msft  thanks for the PR, really nice improvements