Updated overview to include mention of Azure.Identity package.
dotnet/AspNetCore.Docs pull request #24184
Opened 2021-12-03 10:19 UTC by markmcgookin

Fixes #24096 - By mentioning and linking to the Azure.Identity package, as it is required for keyvault authentication.

2021-12-03 10:30 UTC, markmcgookin commented
Mentioning #22546 here as well, as the bot doesn't seem to have picked it up from editing the original message.

2021-12-03 10:36 UTC, serpent5 commented
Hi @markmcgookin. Thanks for this PR. I'll leave it for @Rick-Anderson to review later, but just as an FYI, if you want to link more than one issue, just include `Fixes` for each issue. e.g.:

```
Fixes #24096.
Fixes #22546.
```

-or-

```
Fixes #24096. Fixes #22546.
```

That works when you edit an existing comment too.

2021-12-04 00:56 UTC, Rick-Anderson requested changes

2021-12-04 00:56 UTC, Rick-Anderson commented on aspnetcore/security/data-protection/configuration/overview.md
> +In order for your application to communicate and authorise itself with KeyVault, you must also include the [Azure.Identity](https://www.nuget.org/packages/Azure.Identity/) package within your solutio
```suggestion
For an app to communicate and authorize itself with KeyVault,  the [Azure.Identity](https://www.nuget.org/packages/Azure.Identity/) package  must be added.
```

2021-12-04 00:56 UTC, Rick-Anderson commented on aspnetcore/security/data-protection/configuration/overview.md
> +and [Azure.Extensions.AspNetCore.DataProtection.Keys](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Keys). These packages are where new updates will be provided, and addre
```suggestion
If the app uses the older Azure packages (Microsoft.AspNetCore.DataProtection.AzureStorage and Microsoft.AspNetCore.DataProtection.AzureKeyVault), we recommend ***removing*** these references and upgrading to the [Azure.Extensions.AspNetCore.DataProtection.Blobs](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Blobs) and [Azure.Extensions.AspNetCore.DataProtection.Keys] https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Keys). These packages are where new updates are provided, and address some key security and stability issues with the older packages.
```

2021-12-09 19:44 UTC, Rick-Anderson commented
@markmcgookin  can you review my suggestions?

![image](https://user-images.githubusercontent.com/3605364/145464916-63c017c4-c2ba-4d93-bb8f-65f75bf35c75.png)

2021-12-09 19:57 UTC, markmcgookin commented
That should be it now @Rick-Anderson

2021-12-09 20:12 UTC, merged