No source when property value is empty
dotnet/AspNetCore.Docs pull request #24905
Opened 2022-02-07 08:11 UTC by yecril71pl

When a default value for property is non-empty and the value passed by the client is empty, the default value wins.

```C#
[Required]
public string Test { get; set; } = "!";
```

```cshtml
<input asp-for="Test" >
```

2022-02-10 20:44 UTC, yecril71pl commented
> Hi @yecril71pl. This particular section describes model-binding errors, so I don't see the connection between your example and generating a model-state error. The suggested change describes a form of precedence, but doesn't alter how model-binding works, AFAICT. Would you like to provide more information around the motivation for this change?

After reading the documentation, I expected the empty value sent by the browser to replace the default value, which should be preserved only if the parameter in question is not sent at all.  This does not happen.

2022-02-22 15:12 UTC, serpent5 commented
This isn't the correct place for this change. Consider the following URL:

```
https://localhost:5001/Test?someValue=
```

Here, the value for `someValue` is empty. If I have a model with `[Required]` applied to its `SomeValue` property, a model-binding error _is_ generated using the preceding URL. The change in this PR suggests that an error _isn't_ generated, but it is.

2022-02-22 15:15 UTC, serpent5 requested changes
This isn't the correct place for this change. Consider the following URL:

```
https://localhost:5001/Test?someValue=
```

Here, the value for `someValue` is empty. If I have a model with `[Required]` applied to its `SomeValue` property, a model-binding error _is_ generated using the preceding URL. The change in this PR suggests that an error _isn't_ generated, but it is.

2022-02-23 16:41 UTC, yecril71pl commented
> This isn't the correct place for this change. Consider the following URL:
> 
> ```
> https://localhost:5001/Test?someValue=
> ```
> 
> Here, the value for `someValue` is empty. If I have a model with `[Required]` applied to its `SomeValue` property, a model-binding error _is_ generated using the preceding URL. The change in this PR suggests that an error _isn't_ generated, but it is.

If `someValue` has a default value of `"!"` and an empty value is passed as a parameter (I experimented with `POST` parameters), the empty value is ignored, the property gets the default value, which is non-`null`, therefore no error is generated.

2022-03-03 12:33 UTC, serpent5 commented
Ok, perhaps there's a difference between GET and POST, or between URL mapping and forms-handling. Regardless of where the difference is, the current coverage of this suggests that the default value will be used in all situations, but I think we can agree that this isn't true.

2022-03-04 13:16 UTC, yecril71pl commented
> Ok, perhaps there's a difference between GET and POST, or between URL mapping and forms-handling. Regardless of where the difference is, the current coverage of this suggests that the default value will be used in all situations, but I think we can agree that this isn't true.

I do not know about all situations, I only wrote what I saw: that the default value overrides an empty value explicitly sent by the client.  Which is unexpected.

2022-03-15 10:56 UTC, serpent5 commented
Hi @yecril71pl. I'm closing this PR for reasons I've explained above. I agree that the behaviour you describe exists, but this is neither the correct place for the remark nor exhaustive enough in explaining the exact scenario where said behaviour occurs. If you feel strongly about adding an explanation, please do open a new PR with a more appropriate location and detailed explanation.

2022-03-15 10:56 UTC, closed without merging

2022-03-15 18:53 UTC, yecril71pl commented
This variety and inconsistency suggests it is a bug that needs to be fixed rather than a feature that needs to be documented.