confusing overriding of variables
dotnet/AspNetCore.Docs pull request #25496
Opened 2022-04-01 19:20 UTC by pkellner

I see this a lot and I always think it's a bad practice. Not sure "b" is the right choice,but "builder" is definitely one of the few wrong choices.

2022-04-02 21:12 UTC, serpent5 commented
We don't use single-letter names in the docs, so I suggest `policy` as something that's consistent with e.g. [the authz policies article](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0).

2022-04-02 21:13 UTC, serpent5 reviewed
We don't use single-letter names in the docs, so I suggest `policy` as something that's consistent with e.g. [the authz policies article](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/policies?view=aspnetcore-6.0).

2022-04-04 23:53 UTC, Rick-Anderson requested changes

2022-04-04 23:53 UTC, Rick-Anderson commented on aspnetcore/security/cors/6.0sample/Cors/WebAPI/Program.cs
> +                      b =>
```suggestion
                      policy  =>
```

2022-04-04 23:53 UTC, Rick-Anderson commented on aspnetcore/security/cors/6.0sample/Cors/WebAPI/Program.cs
> +                          b.WithOrigins("http://example.com",
```suggestion
                          policy.WithOrigins("http://example.com",
```

2022-04-05 18:24 UTC, serpent5 approved these changes

2022-04-05 18:46 UTC, Rick-Anderson approved these changes

2022-04-05 18:46 UTC, merged

2022-04-06 01:49 UTC, pkellner commented
Wow!  Thank you for fixing this.

2022-04-06 01:54 UTC, Rick-Anderson commented
@pkellner  thanks for pointing it out. You get the commit credit.