Inconsistency fixed when updating appsettings.
dotnet/AspNetCore.Docs pull request #25551
Opened 2022-04-07 08:50 UTC by baseTwo

Fix for issue #25550 

The bullet (below) mentions that |Microsoft.Hosting.Lifetime| should be removed from the appsettings, but the diff example underneath shows erroneously that "Microsoft":"Warning" should be removed too

"Microsoft.Hosting.Lifetime": "Information" was removed from both appsettings.json and appsettings.Development.json:
- "Microsoft": "Warning", <---- This was removed
- "Microsoft.Hosting.Lifetime": "Information"
+ "Microsoft.AspNetCore": "Warning"

2022-04-07 09:37 UTC, serpent5 requested changes
Hi @baseTwo. Thanks for taking the time to open a pull request and associated issue.

The 5.0 `appsettings.json` file has this section:

```json
"LogLevel": {
  "Default": "Information",
  "Microsoft": "Warning",
  "Microsoft.Hosting.Lifetime": "Information"
}
```

The 6.0 version looks like this:

```json
"LogLevel": {
  "Default": "Information",
  "Microsoft.AspNetCore": "Warning"
}
```

This shows that the sample in the article is correct, but the explanation doesn't mention that `"Microsoft": "Warning"` was replaced with `"Microsoft.AspNetCore": "Warning"`. I think the best resolution here is to update the text to mention that additional change.

2022-04-07 14:51 UTC, baseTwo commented
The only change necessary going from .net 5 to 6 is the replacement of "Microsoft.Hosting.Lifetime" with "Microsoft.AspNetCore"

We found that when removing  "Microsoft":"Warning" , our logs were more noisy. Perhaps it would be better to keep it there in appsettings.json?

2022-04-07 15:51 UTC, serpent5 commented
This section describes the difference between the 5.0 and 6.0 templates. If we don't remove the `"Microsoft":"Warning"` line, it's an inaccurate description of said changes.

2022-04-08 01:39 UTC, closed without merging

2022-04-08 01:40 UTC, Rick-Anderson commented
@baseTwo  let me know if you're interested fixing via mention that `"Microsoft": "Warning"` was replaced with `"Microsoft.AspNetCore": "Warning"`.

2022-04-08 19:29 UTC, baseTwo commented
@Rick-Anderson sure I'll fix mid next week. Out of office until then