Update anti-request-forgery.md
dotnet/AspNetCore.Docs pull request #25585
Opened 2022-04-08 22:45 UTC by nbellowe

2022-04-08 22:45 UTC, nbellowe commented
See https://github.com/dotnet/AspNetCore.Docs/issues/25564

2022-04-09 00:13 UTC, Rick-Anderson requested changes
Expand on the error.

2022-04-09 00:13 UTC, Rick-Anderson commented on aspnetcore/security/anti-request-forgery.md
> +With the Synchronizer Token Pattern, only the most recently loaded page contains a valid antiforgery token. This can raise problems for users with multiple tabs. For example, if a user opens two dist
```suggestion
With the Synchronizer Token Pattern, only the most recently loaded page contains a valid antiforgery token. Using multiple tabs can be problematic. For example, if a user opens multiple tabs:

 * Only the most recently loaded tab contains a valid antiforgery token.
 * Requests made from previously loaded tabs fail with an xyz error.
 
 Consider alternative CSRF protection patterns if this poses an issue.
```

2022-04-15 16:26 UTC, nbellowe commented
@Rick-Anderson  would you mind reviewing again

2022-04-15 17:38 UTC, Rick-Anderson approved these changes

2022-04-19 08:59 UTC, serpent5 approved these changes

2022-04-19 17:43 UTC, merged

2022-04-19 17:44 UTC, Rick-Anderson commented
Thanks for the contribution. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.