AuthZ instead of AuthN
dotnet/AspNetCore.Docs pull request #25633
Opened 2022-04-14 21:15 UTC by michaellyoungg

Page improperly uses AuthN terminology instead of AuthZ

2022-04-15 05:29 UTC, Rick-Anderson commented
No, the article is correct. Look at the API
```
.RequireAuthenticatedUser()
```

2022-04-15 05:35 UTC, Rick-Anderson approved these changes

2022-04-15 05:41 UTC, Rick-Anderson requested changes

2022-04-15 05:41 UTC, Rick-Anderson commented on aspnetcore/security/authorization/secure-data.md
> +Setting the fallback authorization policy to require users to be authenticated protects newly added Razor Pages and controllers. Having authorization required by default is more secure than relying o
```suggestion
Setting the fallback authorization policy to require users to be authenticated protects newly added Razor Pages and controllers. Having authentication required by default is more secure than relying on new controllers and Razor Pages to include the `[Authorize]` attribute.
```

2022-04-15 05:41 UTC, Rick-Anderson commented on aspnetcore/security/authorization/secure-data.md
> +* Is applied to all requests that do not explicitly specify an authorization policy. For requests served by endpoint routing, this would include any endpoint that does not specify an authorization at
```suggestion
* Is applied to all requests that don't explicitly specify an authorization policy. For requests served by endpoint routing, this includes any endpoint that doesn't specify an authorization attribute. For requests served by other middleware after the authorization middleware, such as [static files](xref:fundamentals/static-files), this applies the policy to all requests.
```

2022-04-19 08:58 UTC, serpent5 approved these changes

2022-04-19 08:58 UTC, merged

2022-04-19 08:58 UTC, serpent5 commented
Thanks for your contribution, @michaellyoungg. Be sure to check [What's New](https://docs.microsoft.com/en-us/aspnet/core/whats-new) early next month, where you'll see yourself listed as a valued contributor.