Clarify the relationship of ASP.NET Identity, IdentityServer4 and Microsoft identity platform
dotnet/AspNetCore.Docs pull request #25765
Opened 2022-04-28 14:52 UTC by PeterDraex

I found it challenging to understand the relationship of ASP.NET Identity, Duende IdentityServer4 and Microsoft identity platform. I hope this change can make it easier for others.

2022-04-28 14:57 UTC, PeterDraex commented
@Rick-Anderson I think you'd be the right reviewer here :)

2022-04-28 18:31 UTC, Rick-Anderson requested changes

2022-04-28 18:31 UTC, Rick-Anderson commented on aspnetcore/security/authentication/identity.md
> +* An alternative identity solution for authentication and authorization in ASP.NET Core applications.
```suggestion
* An alternative identity solution for authentication and authorization in ASP.NET Core apps.
* Not related to ASP.NET Core Identity.
```

2022-04-28 18:31 UTC, Rick-Anderson commented on aspnetcore/security/authentication/identity.md
> +* An alternative identity solution for authentication and authorization in ASP.NET Core applications.
```suggestion
* An alternative identity solution for authentication and authorization in ASP.NET Core apps.
* Not related to ASP.NET Core Identity.
```

2022-05-06 21:53 UTC, Rick-Anderson approved these changes

2022-05-06 21:53 UTC, merged

2022-05-06 21:53 UTC, Rick-Anderson commented
Thanks for the contribution. Be sure to check out your name as a contributor about the 3rd of next month on the [What's new page](https://docs.microsoft.com/en-us/aspnet/core/whats-new/) in the **Community contributors** section at the bottom.