Update response-compression.md
dotnet/AspNetCore.Docs pull request #26173
Opened 2022-06-18 13:55 UTC by mmarinchenko

Fixes #22479

2022-06-20 22:50 UTC, Rick-Anderson commented
@mmarinchenko  thanks for the PR. Unfortunately creating a new moniker range is impossible for us to verify and review. I created a new 7.0 moniker range. Unfortunately GitHub is not very good and showing just the changes you made.

2022-06-21 07:23 UTC, mmarinchenko commented
@Rick-Anderson thanks!👍

I've resolved conflicts so the proposed changes can now be reviewed.

2022-06-21 21:50 UTC, Rick-Anderson requested changes

2022-06-22 04:33 UTC, mmarinchenko commented on aspnetcore/performance/response-compression.md
> +| [`Content-Type`](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Type)     | Specifies the [MIME type](https://developer.mozilla.org/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the cont
The MIME types section contains exactly the same link to the source code. If this link needs to be changed in the future, one will need to find out that there are two of them in the document, and change both.

It is much more convenient to have one external link and refer to the corresponding section in the rest of the document. If it makes no sense to refer to a section inside a document, why do we need this section at all?

2022-06-22 04:34 UTC, mmarinchenko commented on aspnetcore/performance/response-compression.md
> +| [`Content-Type`](https://developer.mozilla.org/docs/Web/HTTP/Headers/Content-Type)     | Specifies the [MIME type](https://developer.mozilla.org/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the cont
Same here - https://github.com/dotnet/AspNetCore.Docs/pull/26173#discussion_r903271949

2022-06-22 04:41 UTC, mmarinchenko commented on aspnetcore/performance/response-compression.md
> +The response compression middleware specifies a [default set of MIME types for compression](https://github.com/dotnet/aspnetcore/blob/v6.0.0/src/Middleware/ResponseCompression/src/ResponseCompression
I'm OK with that, but why duplicate (well, almost, but still) a link in two sentences?🙂

I think the first one should be eliminated then.

2022-06-22 05:20 UTC, mmarinchenko commented
> I'll probably swap 6 and 7 but my questions is why do we even need a 7 branch of we point at the source code?

> What in the PR requires a 7.0 moniker section/version?

Without explicit MIME types list - nothing)

I removed explicit list and 7.0 moniker.

2022-06-22 05:22 UTC, mmarinchenko commented on aspnetcore/performance/response-compression.md
> +When compressing responses based on the [`Accept-Encoding` request header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding), there are can be uncompressed and multiple compr
Done as part of 7.0 moniker removal.

2022-06-22 05:22 UTC, mmarinchenko commented on aspnetcore/performance/response-compression.md
> +* [Response compression middleware source](https://github.com/dotnet/aspnetcore/tree/v6.0.0/src/Middleware/ResponseCompression/src)
Done.

2022-06-22 05:23 UTC, mmarinchenko commented on aspnetcore/performance/response-compression.md
> +[View or download sample code](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/performance/response-compression/samples/3.x) ([how to download](xref:index#how-to-download-a-sample))
Done.

2022-06-22 05:23 UTC, mmarinchenko commented on aspnetcore/performance/response-compression.md
> +Explore the features of the Response Compression Middleware with the [sample app](https://github.com/dotnet/AspNetCore.Docs/tree/main/aspnetcore/performance/response-compression/samples/3.x). The sam
Done.

2022-06-22 13:31 UTC, mmarinchenko commented
> * The new 7.0 content is at the **top** of the article's markdown, so it didn't get your, Rick, workaround for broken links until we get to November.

Just for your information, I originally added the 7.0 content to the top because I found the same thing in the [Kestrel Endpoints](https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/fundamentals/servers/kestrel/endpoints.md) document.

2022-06-23 23:28 UTC, Rick-Anderson approved these changes

2022-06-23 23:28 UTC, merged