Minimal api typedresults sample
dotnet/AspNetCore.Docs pull request #26438
Opened 2022-07-15 02:28 UTC by sammychinedu2ky

Made a new pull request here https://github.com/dotnet/AspNetCore.Docs/pull/26437

2022-07-15 09:00 UTC, 5ryde commented
commit

2022-07-16 00:24 UTC, Rick-Anderson requested changes
Select "Add suggestion

2022-07-16 00:24 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/misc-samples/typedResults/TypedResultsApiWithTest/Test/WeatherApiTest.cs
> +}
Git hub like a blank line at the end of a file
![image](https://user-images.githubusercontent.com/3605364/179326772-2ba3977b-6bd8-44ad-b3ee-ee45996f9416.png)
```suggestion
}

```

2022-07-16 00:24 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/misc-samples/typedResults/TypedResultsApiWithTest/Program.cs
> +        // return a typed result
```suggestion
```

2022-07-16 00:24 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/misc-samples/typedResults/TypedResultsApiWithTest/Test/WeatherApiTest.cs
> +            // assert that the result is a typed result of type WeatherForecast[]
```suggestion
```

2022-07-16 00:24 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/misc-samples/typedResults/TypedResultsApiWithTest/Program.cs
> +
```suggestion
```

2022-07-16 05:09 UTC, sammychinedu2ky commented
I mistakenly didn't do the add-to batch ... would ensure I use that next time

2022-07-16 06:39 UTC, sammychinedu2ky commented
@Rick-Anderson please which extension do you use for linting purposes for C#

2022-07-19 02:49 UTC, Rick-Anderson commented
> @Rick-Anderson please which extension do you use for linting purposes for C#

Just what Visual Studio warns. @guardrex  do you use a linter?

2022-07-19 03:11 UTC, Rick-Anderson commented
Moved to #26463

2022-07-19 03:11 UTC, closed without merging

2022-07-19 04:44 UTC, sammychinedu2ky commented
> > @Rick-Anderson please which extension do you use for linting purposes for C#
> 
> Just what Visual Studio warns. @guardrex do you use a linter?

Ooh alright