Update simple.md
dotnet/AspNetCore.Docs pull request #27804
Opened 2022-12-01 00:36 UTC by Rick-Anderson

Fixes #26332

@Blackclaws please review

2022-12-05 08:20 UTC, Blackclaws requested changes
I've tried to make the first statement a bit more concise and expanded the second statement a bit because it didn't exactly fit what's happening.

2022-12-05 08:20 UTC, Blackclaws commented on aspnetcore/security/authorization/simple.md
> +> * Any related authentication is still be done.
Would change to: Authentication middleware is not short-circuited but doesn't need to succeed.

2022-12-05 08:20 UTC, Blackclaws commented on aspnetcore/security/authorization/simple.md
> +> * Any `[Authorize]` attributes on the same controller or action methods on the controller, the authorization requirements specified by `[Authorize]` ware ignored.
Any authorization requirements from `[Authorize]` attributes on the same controller or action methods on the controller are ignored.

2023-01-05 01:19 UTC, Rick-Anderson commented on aspnetcore/security/authorization/simple.md
> +> * Any `[Authorize]` attributes on the same controller or action methods on the controller, the authorization requirements specified by `[Authorize]` ware ignored.
```suggestion
> * Any authorization requirements from `[Authorize]` attributes on the same controller or action methods on the controller are ignored.
```

2023-01-05 01:20 UTC, Rick-Anderson commented on aspnetcore/security/authorization/simple.md
> +> * Any related authentication is still be done.
```suggestion
> * Authentication middleware is not short-circuited but doesn't need to succeed.
```

2023-01-05 01:50 UTC, merged

2023-01-05 01:51 UTC, Rick-Anderson commented
@Blackclaws can you review the published doc. If you'd like changes, can you PR it? 
At the top right of the article, select the Edit pen icon:

![image](https://user-images.githubusercontent.com/3605364/53368931-11972200-38ee-11e9-86ce-18aaff69c719.png)

Select the pen icon again. Save.