Cloud authentication AAD B2C
dotnet/AspNetCore.Docs pull request #27918
Opened 2022-12-16 08:59 UTC by damienbod

fixes https://github.com/dotnet/AspNetCore.Docs/issues/27793

2022-12-16 09:05 UTC, damienbod commented
@JandosKh I created a PR for this now. Points 1-3 are fixed. I removed the AAD auth demo and only have docs for user flows which is the way to authenticate when using B2C. 

Point 4 TenantId is required for Microsoft.Identity.Web

Point 5 is Azure App registration docs for B2C, I think we should just link this in the docs. Opinions?

@Rick-Anderson @CamSoper 

Tested this using .NET 7 and updated the demo snippets.

2022-12-16 12:00 UTC, JandosKh commented
Thank you for PR.
Regarding point 5, I think it will suffice if the doc contains a link to
Azure App registration docs for B2C.


On Fri, Dec 16, 2022 at 6:05 PM damienbod ***@***.***> wrote:

> @JandosKh <https://github.com/JandosKh> I created a PR for this now.
> Points 1-3 are fixed. I removed the AAD auth demo and only have docs for
> user flows which is the way to authenticate when using B2C.
>
> Point 4 TenantId is required for Microsoft.Identity.Web
>
> Point 5 is Azure App registration docs for B2C, I think we should just
> link this in the docs. Opinions?
>
> @Rick-Anderson <https://github.com/Rick-Anderson> @CamSoper
> <https://github.com/CamSoper>
>
> Tested this using .NET 7 and updated the demo snippets.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/AspNetCore.Docs/pull/27918#issuecomment-1354419002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADUF5E2LISVXY4C53IWKYZ3WNQWFXANCNFSM6AAAAAATAU76ZE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-16 22:51 UTC, Rick-Anderson commented on aspnetcore/security/authentication/azure-ad-b2c.md
> +
```suggestion
> [!NOTE]
> Use the profile which matches the Azure App registration **Redirect URIs**
```

2022-12-16 22:52 UTC, Rick-Anderson commented
@damienbod  I did a commit to fix the build so you'll have to pull before you push to prevent conflicts.

2022-12-23 11:37 UTC, damienbod commented
I get all my ASP.NET Core Azure AD and Azure AD B2C docs from here:

https://github.com/AzureAD/microsoft-identity-web

@Rick-Anderson 

Would that be enough? Or should we cross ref. other docs?

2023-01-04 01:30 UTC, Rick-Anderson commented
@CamSoper please review or request another reviewer.

2023-01-05 00:51 UTC, CamSoper requested changes
LGTM! Couple of small changes. Two for formatting, one for phrasing.

2023-01-05 00:51 UTC, CamSoper commented on aspnetcore/security/authentication/azure-ad-b2c.md
> +1. In `Pages/Shared/_Layout.cshtml`, add the highlighted line within the `<header>` element:
```suggestion
1. In *Pages/Shared/_Layout.cshtml*, add the highlighted line within the `<header>` element:
```

2023-01-05 00:51 UTC, CamSoper commented on aspnetcore/security/authentication/azure-ad-b2c.md
> +1. In `Program.cs`, make the following changes:
```suggestion
1. In *Program.cs*, make the following changes:
```

2023-01-05 00:51 UTC, CamSoper commented on aspnetcore/security/authentication/azure-ad-b2c.md
> +    1. Update the `builder services` with the following code:
```suggestion
    1. Update the `builder. Services` lines with the following code:
```

2023-01-05 00:55 UTC, CamSoper commented
Oh and @damienbod I cannot thank you enough for doing this!

2023-01-05 08:00 UTC, damienbod commented on aspnetcore/security/authentication/azure-ad-b2c.md
> +1. In `Pages/Shared/_Layout.cshtml`, add the highlighted line within the `<header>` element:
fixed

2023-01-05 08:00 UTC, damienbod commented on aspnetcore/security/authentication/azure-ad-b2c.md
> +1. In `Program.cs`, make the following changes:
fixed

2023-01-05 08:00 UTC, damienbod commented on aspnetcore/security/authentication/azure-ad-b2c.md
> +    1. Update the `builder services` with the following code:
fixed

2023-01-05 08:01 UTC, damienbod commented
@CamSoper Thanks for the review and the feedback. Updated to PR.

2023-01-05 20:53 UTC, CamSoper approved these changes

2023-01-05 20:54 UTC, merged