Update anti-request-forgery.md
dotnet/AspNetCore.Docs pull request #28425
Opened 2023-02-16 23:55 UTC by Rick-Anderson

Fixes #13024

2023-02-16 23:56 UTC, Rick-Anderson commented
@mhintzke please review

2023-02-17 16:23 UTC, skykick-cm-2 requested changes
This looks great! One typo: `eternal` I think is meant to be `external`. Other than that looks good.

2023-02-17 16:25 UTC, mhintzke commented
This looks great! One typo: `eternal I think is meant to be `external`. Other than that looks good.

2023-02-17 18:00 UTC, Rick-Anderson commented on aspnetcore/security/anti-request-forgery.md
> +When a user is authenticated, they're issued a token (not an antiforgery token). The token contains user information in the form of [claims](/dotnet/framework/security/claims-based-identity-model) or
```suggestion
When a user is authenticated, they're issued a token (not an antiforgery token). The token contains user information in the form of [claims](/dotnet/framework/security/claims-based-identity-model) or a reference token that points the app to user state maintained in the app. When a user attempts to access a resource that requires authentication, the token is sent to the app with an extra authorization header in the form of a Bearer token. This approach makes the app stateless. In each subsequent request, the token is passed in the request for server-side validation. This token isn't *encrypted*; it's *encoded*. On the server, the token is decoded to access its information. To send the token on subsequent requests, store the token in the browser's local storage. Placing a token in the browser local storage and retrieving it and using it as a bearer token provides protection against CSRF attacks. However, should the app be vulnerable to script injection via XSS or a compromised external javascript file, an attacker could retrieve any value from local storage and send it to themselves. ASP.NET Core encodes all server side output from variables by default, reducing the risk of XSS. If you override this behavior by using [Html.Raw](xref:System.Web.Mvc.HtmlHelper.Raw%2A) or custom code with untrusted input then you may increase the risk of XSS.
```

2023-02-17 18:05 UTC, merged