Component parameter value guidance updates
dotnet/AspNetCore.Docs pull request #28696
Opened 2023-03-16 23:31 UTC by guardrex

Fixes #28694

This is a bit quick, but I don't like inaccurate docs ***and don't*** 🛌💤 ***well when I know that there's a problem***.

Dan, we can fix this up and get it in right now if you like. Note tho that the build system is choking at the moment 😈, so I won't be able to take it live until they fix the problem.

Also note that this topic is one of the handful that hasn't been reached to drop the *Whole-topic Versioning*, so there are four copies of the text here. Resolving it down to ***one copy*** 👍 is an on-going task this year, and I'll get to this topic soon enough! 😄

2023-03-17 15:36 UTC, danroth27 commented on aspnetcore/blazor/components/index.md
> +A leading [Razor reserved `@` symbol](xref:mvc/views/razor#razor-syntax) isn't required for component parameters of any type. A leading `@` symbol is optional for non-string parameters and is only re
```suggestion
Assign a C# field, property, or result of a method to a component parameter as an HTML attribute value. The value of the attribute can typically be any C# expression that matches the type of the parameter. The value of the attribute can optionally lead with a [Razor reserved `@` symbol](xref:mvc/views/razor#razor-syntax), but it isn't required.
```

2023-03-17 15:41 UTC, danroth27 commented on aspnetcore/blazor/components/index.md
> +The following `ParameterParent2` component displays four instances of the preceding `ParameterChild` component and sets their `Title` parameter values to:
```suggestion

If the component parameter is of type string, then the attribute value is instead treated as a C# string literal by default.  If you want to specify a C# expression instead, then use the `@` prefix.

The following `ParameterParent2` component displays four instances of the preceding `ParameterChild` component and sets their `Title` parameter values to:
```

2023-03-17 15:42 UTC, danroth27 commented on aspnetcore/blazor/components/index.md
> +The `@` prefix is required for string-typed parameters in a C# context. Otherwise, the framework assumes that a string literal is set. The `@` prefix is ***never*** required for other, non-literal ty
```suggestion
```

2023-03-17 15:45 UTC, danroth27 requested changes
Some suggested edits.

2023-03-17 16:48 UTC, guardrex commented
@danroth27 ... I think that gets it. Let me know if you want me to wait for Steve to look 👀.

2023-03-20 09:28 UTC, SteveSandersonMS approved these changes
Looks good

2023-03-20 18:58 UTC, merged