Add IPC security section
dotnet/AspNetCore.Docs pull request #29973
Opened 2023-08-02 06:10 UTC by JamesNK

@blowdart @GrabYourPitchforks Security guidance for named pipes IPC (and IPC in general)

2023-08-02 11:56 UTC, gfoidl commented on aspnetcore/grpc/interprocess.md
> +Another option for securing a IPC server is to use authentication and authorization built into ASP.NET Core. For example, the server could be configured to require [certificate authentication](https:
```suggestion
Another option for securing a IPC server is to use authentication and authorization built into ASP.NET Core. For example, the server could be configured to require [certificate authentication](https://learn.microsoft.com/aspnet/core/security/authentication/certauth). RPC calls made by client apps without the required certificate fail with an unauthorized response.
```

2023-08-04 17:31 UTC, blowdart approved these changes

2023-08-04 17:31 UTC, blowdart commented on aspnetcore/grpc/interprocess.md
> +
Commit to making sure this advice is on the docs page for enabling IPC

2023-08-04 17:31 UTC, blowdart commented on aspnetcore/grpc/interprocess.md
> +```
Needs public docs before release

2023-08-04 17:31 UTC, blowdart commented on aspnetcore/grpc/interprocess.md
> +
And you know already, describe this publically

2023-08-05 02:27 UTC, Rick-Anderson requested changes

2023-08-05 02:27 UTC, Rick-Anderson commented on aspnetcore/grpc/interprocess.md
> +* Named pipes supports securing a pipe with the [Windows access control model](https://learn.microsoft.com/windows/win32/ipc/named-pipe-security-and-access-rights). Access rights can be configured in
```suggestion
* Named pipes supports securing a pipe with the [Windows access control model](/windows/win32/ipc/named-pipe-security-and-access-rights). Access rights can be configured in .NET when a server is started using the <xref:System.IO.Pipes.PipeSecurity> class.
```

2023-08-05 02:27 UTC, Rick-Anderson commented on aspnetcore/grpc/interprocess.md
> +Another option for securing a IPC server is to use authentication and authorization built into ASP.NET Core. For example, the server could be configured to require [certificate authentication](https:
```suggestion
Another option for securing a IPC server is to use authentication and authorization built into ASP.NET Core. For example, the server could be configured to require [certificate authentication](xref:security/authentication/certauth). RPC calls made by client apps without the required certificate fail with an unauthorized response.
```

2023-08-05 02:27 UTC, Rick-Anderson commented on aspnetcore/grpc/interprocess.md
> +Another option for validating the server is to [secure its endpoints with HTTPS](https://learn.microsoft.com/aspnet/core/fundamentals/servers/kestrel/endpoints#configure-https) inside ASP.NET Core. T
```suggestion
Another option for validating the server is to [secure its endpoints with HTTPS](/aspnet/core/fundamentals/servers/kestrel/endpoints#configure-https) inside ASP.NET Core. The client can configure `SocketsHttpHandler` to validate the server is using the expected certificate when the connection is established.
```

2023-08-05 02:27 UTC, Rick-Anderson commented on aspnetcore/grpc/interprocess.md
> +Named pipes supports a feature called [impersonation](https://learn.microsoft.com/windows/win32/ipc/impersonating-a-named-pipe-client). Using impersonation, the named pipes server can execute code wi
```suggestion
Named pipes supports a feature called [impersonation](/windows/win32/ipc/impersonating-a-named-pipe-client). Using impersonation, the named pipes server can execute code with the privileges of the client user. This is a powerful feature but can allow a low-privilege server to impersonate a high-privilege caller and then run malicious code.
```

2023-08-05 03:11 UTC, Rick-Anderson approved these changes

2023-09-05 00:51 UTC, merged