VS Code: Add required assets
dotnet/AspNetCore.Docs pull request #30363
Opened 2023-09-14 19:02 UTC by wadepickett

Fixes #30163
.
For creating a new project particular to the tutorial, and then building and running there was an assumed step that was missing.  Added the following.

1.  Call out the add assets prompt, which occurs after the **trust the authors** dialog.
2.  Since there are a few ways it is possible to not get or miss the prompt for adding assets point out that if this step was missed or unavailable, select **View** > **Command Palette** and enter *.NET: Generate Assets for Build and Debug*. 

There are a couple of lines of instruction that repeat across the getting started tutorials and I may move it to an include yet.  However, there are lines between them that are required and specific to just that tutorial and project type, so it is not the most useful example for an include which can cost some time and effort with each update trying to deal with jumping back and forth to keep the formatting working with it, so not a great savings.

2023-09-14 19:42 UTC, guardrex commented
Wade, I found that my guidance in the Blazor *Tooling* doc broke 💥 at some point due to VSC churn, so I pulled it this morning. I don't see the command palette command you mentioned coming up here with my VSC, but I did see that the following produces assets at least headed in the right direction. I don't have a test app running yet with the generated assets, but I have a tracking item to work on it when I get some time.

* For `launch.json`: **Run** > **Add Configuration** > **Edge: Launch**.
* For `tasks.json`: **Terminal** > **Configure Default Build Task** > **Create tasks.json file from template** > **.NET Core Executes .NET Core build command**.

2023-09-14 20:54 UTC, wadepickett commented
@guardrex, thanks.  Just a side note: Installing the C# dev kit extension will conflict with the C# extension's prompt and also keep the prompt from displaying.

2023-09-14 20:55 UTC, guardrex commented
I see. Thx. Yes, I better add that, too. I'll cross-ref your remark to my full issue.

2023-09-14 20:59 UTC, wadepickett commented
@guardrex, I decided not to mention the C# Dev Kit conflict with the add assets prompt in this PR.  There are also a few other reasons why the prompt will not display, so rather than covering all of them I simply said how to run it manually if the prompt did not appear.

 I'm not touching the Blazor tutorials with this PR, although I did look through them to see if we were covering the steps in order or missing any.

2023-09-14 21:05 UTC, guardrex commented
I phrased it this way for the time being ...

https://github.com/dotnet/AspNetCore.Docs/pull/30365/files

... without the C# Dev Kit mention. Even if it were mentioned, it's only a *mention*, not recommendation, given its preview status. I imagine that after release that they'll want it to be recommended.

2023-09-14 21:06 UTC, guardrex commented
BTW ... Do you know if the command palette commands are localized into other languages. I code fenced, but if they get translated, I should covert to just bold text, as you have done here.

2023-09-14 21:10 UTC, guardrex commented
Actually, I'm testing that now. I'll report back.

2023-09-14 21:13 UTC, guardrex commented
😆 ... 🍀 ***Lucky Guess***&trade; 🍀 ... Here's what happened after I switched to Spanish. Yeah ... I'll leave it code fenced. I noticed this problem a lot with VS, too. When I did testing on loc in the VS UI, it was kind'a all over the place. Some stuff was localized, some not localized.

![image](https://github.com/dotnet/AspNetCore.Docs/assets/1622880/645c86a3-8e5e-4055-86f5-544325b7e4cd)

2023-09-14 21:24 UTC, wadepickett commented
OK, I will go with code fenced to, thanks!

2023-09-14 21:28 UTC, guardrex commented
Sure thing. 👍 

The menu bar ***IS*** translated, so I just went bold text for that. That part I was familiar with. VS does the same thing. After that tho, it's 🎲🎲 ***CASINO ODDS*** 🎲🎲 on translations. :smile:

2023-09-19 00:43 UTC, tdykstra requested changes
Looks good except for the "do you trust" question instructions.  You don't need to take my suggestion but I think we should not assume that the answer to these questions is affirmative.

2023-09-19 02:08 UTC, tdykstra commented on aspnetcore/includes/vscode-trust-authors-add-assets.md
> +
And incidentally, this only just occurred to me -- I have to make the same changes to the dotnet/docs VSC tutorials.

2023-09-19 02:31 UTC, tdykstra approved these changes

2023-09-19 03:46 UTC, merged