Http logging in dotnet 8 doesn't work without call AddHttpLogging
dotnet/AspNetCore.Docs pull request #30781
Opened 2023-10-19 21:58 UTC by naeemaei

Based [this issue](https://github.com/dotnet/aspnetcore/issues/51322) on [aspnetcore](https://github.com/dotnet/aspnetcore) repository, HTTP logging without call `AddHttpLogging` method doesn't work and get exception.
I added this line to the doc

2023-10-20 00:52 UTC, tdykstra requested changes
@naeemaei Thanks for reporting this! The change you made is to a file that will be used only for .NET 6 and 7. The code that will be used when ASP.NET Core 8.0 is selected is now in an 8.x folder. If you would like to update the PR to make your change in the 8.x files, I can merge this and will further update the 8.x files to add the new RC2 features.

2023-10-20 18:33 UTC, Tratcher commented on aspnetcore/fundamentals/http-logging/samples/8.x/Program.cs
> +builder.Services.AddHttpLogging();
The new overload `AddHttpLogging()` isn't available until net9.0.
```suggestion
builder.Services.AddHttpLogging(o => { });
```

2023-10-23 18:25 UTC, tdykstra approved these changes

2023-10-23 18:31 UTC, merged

2023-10-23 18:32 UTC, tdykstra commented
Thanks for the fix, @naeemaei !