WIP: SPA authentication and authorization doc
dotnet/AspNetCore.Docs pull request #31010
Opened 2023-11-13 18:16 UTC by tdykstra

Fixes #30066 
Fixes #29363 

The diff is not useful, the .NET 8 content is in effect a new doc.

2023-11-13 19:44 UTC, JeremyLikness requested changes
Few changes. @tdykstra I will also have a sample for tokens with comments right after lunch so we can complete that section.

2023-11-13 22:36 UTC, guardrex reviewed
Passing recommendation to go with `AppUser`. I thought there was a time that we were trying to drop "`My`"-named things, but that just might be my imagination😄.

2023-11-13 22:36 UTC, guardrex commented on aspnetcore/security/authentication/identity-api-authorization.md
> +builder.Services.AddIdentityCore<MyUser>()
```suggestion
builder.Services.AddIdentityCore<AppUser>()
```

2023-11-13 22:36 UTC, guardrex commented on aspnetcore/security/authentication/identity-api-authorization.md
> +Add to the project a class named `MyUser` that inherits from <xref:Microsoft.AspNetCore.Identity.IdentityUser>:
```suggestion
Add to the project a class named `AppUser` that inherits from <xref:Microsoft.AspNetCore.Identity.IdentityUser>:
```

2023-11-13 22:36 UTC, guardrex commented on aspnetcore/security/authentication/identity-api-authorization.md
> +public class MyUser : IdentityUser
```suggestion
public class AppUser : IdentityUser
```

2023-11-13 22:36 UTC, guardrex commented on aspnetcore/security/authentication/identity-api-authorization.md
> +    IdentityDbContext<MyUser>(options)
```suggestion
    IdentityDbContext<AppUser>(options)
```

2023-11-13 22:36 UTC, guardrex commented on aspnetcore/security/authentication/identity-api-authorization.md
> +app.MapIdentityApi<MyUser>();
```suggestion
app.MapIdentityApi<AppUser>();
```

2023-11-13 23:57 UTC, tdykstra commented
@guardrex I'm following the pattern in the simplified code supplied by Jeremy that uses IdentityUser directly.

2023-11-14 00:30 UTC, Rick-Anderson approved these changes

2023-11-14 00:30 UTC, Rick-Anderson commented on aspnetcore/security/authentication/identity-api-authorization.md
> +For more information, see the following resources:
`## Additional resources` is shorter.

2023-11-14 01:54 UTC, JeremyLikness approved these changes
Looks good to me.

2023-11-14 02:45 UTC, merged

2023-11-14 12:08 UTC, guardrex commented
@tdykstra ... Very good. I currently left it the original way that @JeremyLikness had it for the Blazor sample, but I think that's a good approach. I'll make a long-range tracking note to update that sample, but @JeremyLikness can let me know if switching over to `IdentityUser` for that sample app isn't the best choice for some reason. I won't get to that for a little while. I'll probably be swamped with higher priority work all the way to the ⛄ EOY holidays.

2023-11-20 23:36 UTC, JeremyLikness commented
Using `IdentityUser` is preferred unless we're showing how to customize the user.