Fixing Issue #31348
dotnet/AspNetCore.Docs pull request #31349
Opened 2024-01-04 09:42 UTC by Nitzantomer1998

Fixes #31348

Changed two files:
+ Inserted a new image which show how to update the existed form with the new "Rating" field in VScode.
Path of the new file: aspnetcore/tutorials/first-mvc-app/new-field/_static/VSCode-UpdatingForm.png

+ Inserted a new row inside of the visual studio code tab, which shows the needed action in VSCode.
Path of the modified file: aspnetcore/tutorials/first-mvc-app/new-field.md

2024-01-04 19:45 UTC, wadepickett requested changes
Looks great!  Thanks!   Could you add the same update to the .NET 7.0 version of the topic here as well?  (Or I can add it if you like):
aspnetcore/tutorials/first-mvc-app/new-field/includes/new-field7.md

2024-01-04 20:05 UTC, wadepickett commented
@Nitzantomer1998, please disregard change request for version 7.0.   Looking back, the output for the class names were different for those elements in previous versions.   I will approve in a second with your original for version 8.0 and back out of the change I made for versions 5-6.

2024-01-04 20:06 UTC, wadepickett commented on aspnetcore/tutorials/first-mvc-app/new-field/includes/new-field5.md
> +![Updating the existed form by inserting the new field "Rating".](~/tutorials/first-mvc-app/new-field/_static/VSCode-UpdatingForm.png)
```suggestion
<!-- This tab intentionally left blank. -->
```

2024-01-04 20:06 UTC, wadepickett commented on aspnetcore/tutorials/first-mvc-app/new-field/includes/new-field6.md
> +![Updating the existed form by inserting the new field "Rating".](~/tutorials/first-mvc-app/new-field/_static/VSCode-UpdatingForm.png)
```suggestion
<!-- This tab intentionally left blank. -->
```

2024-01-04 20:14 UTC, wadepickett approved these changes
Thanks again!!

2024-01-04 20:14 UTC, merged

2024-01-05 05:23 UTC, Nitzantomer1998 commented
Hey man, I guess our country's timing is completely different.

I saw you made some changes to the older versions and then revert it if
i`m current.
If you need me to check the previous .NET versions and apply the same
change (with modification to the context) I would be happy to do so.

So if needed, let me know and I will do it tomorrow.
Have a good day and keep the good work :), those document really help me to
get started with .NET

On Thu, Jan 4, 2024 at 10:15 PM Wade Pickett ***@***.***>
wrote:

> Merged #31349 <https://github.com/dotnet/AspNetCore.Docs/pull/31349> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/AspNetCore.Docs/pull/31349#event-11394472175>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWHBTERWOXTIRGW2EWL4CA3YM4EULAVCNFSM6AAAAABBMUYDB2VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJRGM4TINBXGIYTONI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>