Updated app-secrets.md to show how to use user secrets in a console app
dotnet/AspNetCore.Docs pull request #31371
Opened 2024-01-05 23:56 UTC by richstokoe

Fixes #31370 

Adds documentation for explicitly using the dotnet user-secrets in projects that target `Microsoft.NET.Sdk` and not the web SDK `Microsoft.NET.Sdk`.

See issue.

2024-01-06 03:50 UTC, tdykstra requested changes
Thanks, @richstokoe ! I made some suggestions for clarity and site style.

2024-01-06 03:50 UTC, tdykstra commented on aspnetcore/security/app-secrets.md
> +
```suggestion

```

2024-01-06 03:50 UTC, tdykstra commented on aspnetcore/security/app-secrets.md
> +Once installed, you can load and use user secrets in your app like this (requires a user secret called "Foo" [to be set](#set-a-secret):
```suggestion
Once the packages are installed, [initialize the project](#enable-secret-storage) and [set secrets](#set-a-secret) the same way as for a web app. The following example shows a console application that retrieves the value of a secret that was set with the key "Foo":
```

2024-01-06 10:01 UTC, richstokoe commented
Thanks @tdykstra - these definitely look better and I've committed them all to the PR.

2024-01-07 21:32 UTC, tdykstra approved these changes
Thanks, @richstokoe

2024-01-07 21:33 UTC, merged

2024-01-18 23:48 UTC, tdykstra commented
@richstokoe We only changed the content that appears when the version selector is set to earlier than ASP.NET Core 6.0. To update what is shown when version 6.0 or later is selected we need to copy the changes in line 312 to line 36 and duplicate lines 317-355 between lines 40 and 41. Would you like to do that? If you don't have time for it, let me know and I'll take care of it.