Enforce HTTPS in ASP.NET Core: Use Status308PermanentRedirect
dotnet/AspNetCore.Docs pull request #31739
Opened 2024-02-08 12:36 UTC by 0xced

The previous paragraph says
> Use the fields of the [StatusCodes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.statuscodes) class for assignments to `RedirectStatusCode`.

But the sample code then uses the status code defined in `System.Net` and a cast to `int`.

2024-02-08 13:03 UTC, guardrex commented
LGTM, but I think Tom is managing the article on this, so I'll ping him for an 👁️.

2024-02-08 17:30 UTC, tdykstra commented on aspnetcore/security/enforcing-ssl/sample-snapshot/6.x/Program3.cs
We should do the same thing for the temporary redirect in the preceding code snippet.

2024-02-20 00:16 UTC, tdykstra requested changes
We should do the same thing for the temporary redirect in the preceding code snippet.

2024-02-27 14:23 UTC, 0xced commented
Good point! Done in 34f3c2d6c8ed3e34242f0516d003c1a3308b7e50.

2024-02-27 19:21 UTC, tdykstra approved these changes
Thanks!

2024-02-27 19:24 UTC, merged