Post-PR review.
dotnet/AspNetCore.Docs pull request #32562
Opened 2024-05-10 21:03 UTC by tdykstra

Review of the article created by #32529 

Mostly changes to conform to the style guide. 
On periods in bulleted lists, see https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=56575

2024-05-10 21:56 UTC, Rick-Anderson commented
Search and replace here -- too verbose
```## Add and configure OpenAPI document generation

ADD the OpenAPI-related services to `Program.cs`: <!-- REPLACE FOLLOWING WITH SNIPPET -->```

2024-05-10 21:57 UTC, Rick-Anderson commented
<img width="206" alt="image" src="https://github.com/dotnet/AspNetCore.Docs/assets/3605364/7226bd17-6483-4f83-8435-a10abee8aa87">

2024-05-10 21:58 UTC, Rick-Anderson commented
> . The requests below will resolve the v1 and internal documents respectively.
The following requests resolve (nuke will)

2024-05-10 22:01 UTC, Rick-Anderson commented
> Transformers are useful for scenarios like:
* adding parameters to all operations in a document, 
* modifying descriptions for parameters or operations, 
* adding top-level information to the OpenAPI document.

2024-05-10 22:10 UTC, Rick-Anderson requested changes
rewrite

Operation transformers apply to each individual operation (combination of path + HTTP method) and can be used to modify parameters or responses on endpoints.

Operation transformers apply to each individual operation, modifying parameters or responses on endpoints. These operations are a combination of the path and the HTTP method.

LInk to source on new APIs, ie
https://github.com/dotnet/aspnetcore/blob/main/src/OpenApi/src/Transformers/IOpenApiDocumentTransformer.cs#L9

2024-05-10 22:19 UTC, Rick-Anderson commented
https://github.com/dotnet/aspnetcore/blob/main/src/OpenApi/src/Services/OpenApiOptions.cs

2024-05-10 22:20 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
> +Transformers can be registered onto the document via the `UseTransformers` call on the `OpenApiOptions` object. The following snippet shows different ways to register transformers onto the document:
```suggestion
Transformers can be registered onto the document via the `UseTransformer` call on the `OpenApiOptions` object. The following snippet shows different ways to register transformers onto the document:
```

2024-05-10 22:22 UTC, Rick-Anderson commented
useTransformer in https://github.com/dotnet/aspnetcore/blob/main/src/OpenApi/src/Services/OpenApiOptions.cs#L47

2024-05-10 22:28 UTC, Rick-Anderson reviewed
aspnetcore\src\Mvc\Mvc.ApiExplorer\src\ApiDescriptionGroupCollectionProvider.cs
contains ApiDescriptionGroups 

Probably create another PR to update these ref when the API is built. It's nice to have a link to the source and the API ref.

2024-05-13 15:07 UTC, captainsafia commented on aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
> +Document transformers are unique to the document instance they are associated with. In the example below, a transformer registers authentication-related requirements to the `internal` document but le
```suggestion
Document transformers are unique to the document instance they are associated with. In the example below, a transformer registers authentication-related requirements to the `internal` document but leaves the `public` document unmodified.

[!code-csharp[](~/fundamentals/minimal-apis/9.0-samples/WebMinOpenApi/Program.cs?name=snippet_multidoc_operationtransformer1)]
```

2024-05-13 18:54 UTC, merged