Document ShutdownDelay
dotnet/AspNetCore.Docs pull request #32637
Opened 2024-05-22 23:02 UTC by tdykstra

Fixes #32600

2024-05-22 23:30 UTC, BrennanConroy commented on aspnetcore/host-and-deploy/iis/advanced.md
> +## Fix for 503's during app recycle in IIS
Not a fan of the title, here's some other thoughts:

Reduce 503 likelihood during app recycle
Delay managed app shutdown during app recycle
Delay server shutdown on recycle

2024-05-22 23:49 UTC, Rick-Anderson requested changes

2024-05-22 23:49 UTC, Rick-Anderson commented on aspnetcore/host-and-deploy/iis/advanced.md
> +By default there is a one second delay between when IIS is notified of a recycle or shutdown and when ANCM tells the managed server to start shutting down. The delay is configurable via the `ANCM_shu
```suggestion
By default there is a one second delay between when IIS is notified of a recycle or shutdown and when ANCM tells the managed server to initiate shutdown. The delay is configurable via the `ANCM_shutdownDelay` environment variable or by setting the `shutdownDelay` handler setting. Both values are in milliseconds. The delay is primarily to reduce the likelihood of a race where:
```

2024-05-22 23:49 UTC, Rick-Anderson commented on aspnetcore/host-and-deploy/iis/advanced.md
> +This setting doesn't mean incoming requests will be delayed by this amount. It just means that the old app instance will start shutting down after this timeout occurs. Slower machines or machines wit
```suggestion
This setting doesn't mean incoming requests will be delayed by this amount. The setting indicates that the old app instance will start shutting down after the timeout occurs. Slower machines or machines with heavier CPU usage might need to adjust this value to reduce 503 likelihood.
```

2024-05-22 23:58 UTC, tdykstra commented on aspnetcore/host-and-deploy/iis/advanced.md
> +## Fix for 503's during app recycle in IIS
```suggestion
## Reduce 503 likelihood during app recycle```

2024-05-23 00:00 UTC, tdykstra commented on aspnetcore/host-and-deploy/iis/advanced.md
> +## Reduce 503 likelihood during app recycle```
```suggestion
## Reduce 503 likelihood during app recycle
```

2024-05-23 00:44 UTC, Rick-Anderson approved these changes

2024-05-23 00:44 UTC, merged