Update key-vault-configuration.md
dotnet/AspNetCore.Docs pull request #32671
Opened 2024-05-26 08:21 UTC by azarboon

"Azure AD" is the old name so I've updated references to "Microsoft Entra ID"

2024-05-27 23:46 UTC, Rick-Anderson commented
We get this PR every month. There are some exceptions, I think this is an exception. If so, update the pr and in a comment `<!-- link to exception and state it's an exception -->`

2024-05-29 00:17 UTC, Rick-Anderson requested changes

2024-05-29 00:17 UTC, Rick-Anderson commented on aspnetcore/security/key-vault-configuration.md
> +* `Managed`: Demonstrates how to use [Managed identities for Azure resources](/azure/active-directory/managed-identities-azure-resources/overview). The managed identity authenticates the app to Azure
```suggestion
* `Managed`: Demonstrates how to use [Managed identities for Azure resources](/azure/active-directory/managed-identities-azure-resources/overview). The managed identity authenticates the app to Azure Key Vault with Managed identities for Azure resources without storing credentials in the app's code or configuration. The `Managed` version of the sample must be deployed to Azure. Follow the guidance in the [Use the managed identities for Azure resources](#use-managed-identities-for-azure-resources) section.
```

2024-05-29 00:34 UTC, Rick-Anderson requested changes

2024-05-29 00:34 UTC, Rick-Anderson commented on aspnetcore/security/key-vault-configuration.md
> +* `Managed`: Demonstrates how to use [Managed identities for Azure resources](/azure/active-directory/managed-identities-azure-resources/overview). The managed identity authenticates the app to Azure
```suggestion
* `Managed`: Demonstrates how to use [Managed identities for Azure resources](/azure/active-directory/managed-identities-azure-resources/overview). The managed identity authenticates the app to Azure Key Vault with Managed identities for Azure resources without credentials stored in the app's code or configuration. When using managed identities to authenticate, a Managed identities for Azure resources app ID and Password (Client Secret) aren't required. The `Managed` version of the sample must be deployed to Azure. Follow the guidance in the [Use the managed identities for Azure resources](#use-managed-identities-for-azure-resources) section.
```

2024-05-29 00:34 UTC, Rick-Anderson commented on aspnetcore/security/key-vault-configuration.md
> +Configure Microsoft Entra ID, Azure Key Vault, and the app to use an Microsoft Entra ID Application ID and X.509 certificate to authenticate to a vault **when the app is hosted outside of Azure**. Fo
```suggestion
Configure Azure Key Vault and the app to use an Microsoft Entra ID Application ID and X.509 certificate to authenticate to a vault **when the app is hosted outside of Azure**. For more information, see [About keys, secrets, and certificates](/azure/key-vault/about-keys-secrets-and-certificates).
```

2024-05-29 00:34 UTC, Rick-Anderson commented on aspnetcore/security/key-vault-configuration.md
> +Configure Microsoft Entra ID, Azure Key Vault, and the app to use an Microsoft Entra ID Application ID and X.509 certificate to authenticate to a vault **when the app is hosted outside of Azure**. Fo
```suggestion
Configure Azure Key Vault and the app to use an Microsoft Entra ID Application ID and X.509 certificate to authenticate to a vault **when the app is hosted outside of Azure**. For more information, see [About keys, secrets, and certificates](/azure/key-vault/about-keys-secrets-and-certificates).
```

2024-05-29 00:43 UTC, Rick-Anderson approved these changes

2024-05-29 01:05 UTC, azarboon commented
@dotnet-policy-service agree

2024-05-29 01:05 UTC, merged