Reassign articles to wpickett
dotnet/AspNetCore.Docs pull request #32870
Opened 2024-06-14 22:28 UTC by wadepickett

Fixes #32831 
Fixes #32830

Per management request, reassigning topics for ms.author that we to watch over, keep up the health on so they are more distributed between writers.

This brings the topic total for me to watch over to **148** total in aspnetcore.docs as asked.

The original or current author is maintained in the `author: ` meta field so it remains clear who the author is and credited to.

Added topics recommended by Tom to take, the areas generally cover:

- OpenAPI
- SignalR
- Docker
- Minimal API
- gRPC
- cient-side libman and SPA
- Any topic that was still listed as scaddie for ms.author
- 6 diagnostic/ error topics since everyone seem to have some of those but me, and I was at a loss for the last 6 to take. Tom didn't originally suggest these 6.

This pr is related to #32852

Feel free to suggest different topics.

2024-06-14 22:30 UTC, wadepickett commented
@tdykstra and @Rick-Anderson, need your feedback on the draft.  Feel free to suggest different articles to switch.

2024-06-14 22:52 UTC, Rick-Anderson requested changes

2024-06-14 22:52 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/aspnetcore-openapi.md
> -ms.author: safia
Keep safia, I'm the backup

2024-06-14 22:52 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/overview.md
> -ms.author: jeliknes
Keep Jermy, we just need to transfer from @Rick-Anderson to @wadepickett

2024-06-14 22:52 UTC, Rick-Anderson commented on aspnetcore/fundamentals/minimal-apis/responses.md
> -ms.author: brolivei
ditto

2024-06-17 14:41 UTC, tdykstra approved these changes

2024-06-17 19:51 UTC, Rick-Anderson approved these changes

2024-06-17 20:09 UTC, wadepickett commented
@JamesNK, I have been asked to identify an equal number of topics between the writers that I will be assigned to monitor the health for and actively maintain (as much as we can fit and prioritize into every sprint).

Part of this involves keeping the author metadata set to the author (for example keep it set to you for gRPC topics) while setting ms.author to the topic areas the doc team writer is dedicating time to.  

I'm giving you a heads up since you are one of the development team's most active in creating new docs and maintaining them (at superhero levels).  I didn't want you to be surprised, and to make sure you understood you still attributed to and maintained as `author` and why we are changing `ms.author`.

2024-06-17 20:11 UTC, merged