Add example for configuring JS collocation in _Layout.cshtml
dotnet/AspNetCore.Docs pull request #33190
Opened 2024-07-27 13:07 UTC by sliekens

This advice should work for Razor pages and for MVC views. I'm not sure about scripts provided by Razor class libraries, I don't use them personally.

2024-08-19 11:17 UTC, guardrex commented
Hello @sliekens ... It's a reasonable tip, but this would need to call out that every page of the layout must have a collocated JS file.

@Rick-Anderson ... Are you interested in this?

2024-08-19 11:50 UTC, sliekens commented
@guardrex I see why you might think that it always adds a script tag to every page, but `asp-src-include` omits the script tag when there are no matching files. So, this allows a mix of pages with and without collocated scripts.

2024-08-19 11:53 UTC, guardrex commented
I see. I looked it up, and it didn't say that was the case ...

https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/script-tag-helper?view=aspnetcore-8.0#asp-src-include

2024-08-19 12:14 UTC, sliekens commented
For context about why this works:

``` html
<!-- <script asp-src-include="@(ViewContext.View.Path).js"></script> -->
<script asp-src-include="/Pages/Index.cshtml.js"></script>
```

The ScriptTagHelper sees there is no `src` attribute, so it deletes the original `<script>` tag.

https://github.com/dotnet/aspnetcore/blob/48a07213d4d8df15c6dffccd161844842c196998/src/Mvc/Mvc.TagHelpers/src/ScriptTagHelper.cs#L307-L313

Then it uses the string `"/Pages/Index.cshtml.js"` as a globbing pattern to find matching files. It then renders a new script tag for each matching file. Since the pattern doesn't include any wildcards (`*`), it should either find 1 or 0 matching files. If no matching file is found, no script tag is rendered.

2024-08-19 12:34 UTC, guardrex commented
> update the PR with a note about this behavior?

Probably best to wait for Rick to see this. It seems harmless enough as a tip. Rick might want to document the underlying behavior in the Script Tag Helper article and cross-link to it from here. The cross-link will probably be to `xref:mvc/views/tag-helpers/built-in/script-tag-helper#asp-src-include`. ***And*** ... he can dissolve the INCLUDE file at the same time.

He'll be along in a few hours ... he's in a different time zone 🌔.

2024-08-19 18:08 UTC, Rick-Anderson requested changes

2024-08-19 18:08 UTC, Rick-Anderson commented on aspnetcore/includes/js-collocation.md
> +  You can configure the default layout `(Pages/Shared/_Layout.cshtml)` to always include collocated JS files, eliminating the need to configure each page individually:
```suggestion
The default layout `(Pages/Shared/_Layout.cshtml)` can be configured to include collocated JS files, eliminating the need to configure each page individually:
```

2024-08-19 19:32 UTC, sliekens commented
@Rick-Anderson sorry, what's an RP sample? 😀

2024-08-19 20:04 UTC, Rick-Anderson commented
> @Rick-Anderson sorry, what's an RP sample? 😀
> 
> /edit: having just realized RP means Razor Pages, what are your expectations for such a sample?

Sorry for using RP, I should have spelled it out. Just the simplest possible sample that demonstrates JS collocation in `_Layout.cshtml` and `asp-src-include` omits the script tag when there are no matching files. So, this allows a mix of pages with and without collocated scripts. 

You can do the sample in another PR and add add closes ` #33400`

2024-08-19 20:15 UTC, Rick-Anderson approved these changes

2024-08-19 20:19 UTC, sliekens commented
Okay @Rick-Anderson I canceled the automerge because I had already pushed a part of the sample to this branch. I will move the changes over to a new PR.

2024-08-19 20:22 UTC, Rick-Anderson commented
@sliekens sorry about that, merging here would have been fine. I didn't realize you could generate a sample that fast and didn't want to hold up this PR. Either way is fine.

2024-08-19 20:57 UTC, sliekens commented
Okay, I pushed the sample to this branch after all.

I used `dotnet new razor`, removed the `Privacy` page and instead added two pages.

1. a page with a collocated JS script
   ![image](https://github.com/user-attachments/assets/b837b39c-a85c-42b8-8ff4-fd842f3827c9)
2. another page without any script
   ![image](https://github.com/user-attachments/assets/73abf5e6-6d0b-4d3a-8af2-00e9657dc731)

2024-08-19 21:05 UTC, sliekens commented
@Rick-Anderson if you could review again, I hope this is what you had in mind.

2024-08-20 05:47 UTC, Rick-Anderson commented
> @Rick-Anderson if you could review again, I hope this is what you had in mind.

Looks great. I'll test it tomorrow.

2024-09-23 21:15 UTC, Rick-Anderson commented on aspnetcore/includes/js-collocation.md
> +The default layout `(Pages/Shared/_Layout.cshtml)` can be configured to include collocated JS files, eliminating the need to configure each page individually:
```suggestion
The default layout `Pages/Shared/_Layout.cshtml` can be configured to include collocated JS files, eliminating the need to configure each page individually:
```

2024-09-23 22:26 UTC, Rick-Anderson commented
@sliekens  moved to #33697, I carried your commit so you'll get credit for the merge.

2024-09-23 22:26 UTC, closed without merging

2024-09-23 22:53 UTC, sliekens commented
Cool, thanks 😎👍