.NET 9: OpenIdConnectHandler adds support for Pushed Authorization Requests (PAR)
dotnet/AspNetCore.Docs pull request #33366
Opened 2024-08-15 08:36 UTC by damienbod

fixes https://github.com/dotnet/AspNetCore.Docs/issues/33332

2024-08-15 20:30 UTC, Rick-Anderson commented
@damienbod  looks great.
@josephdecock please review.

2024-08-16 03:13 UTC, josephdecock requested changes
Otherwise looks good!

2024-08-16 03:13 UTC, josephdecock commented on aspnetcore/security/authentication/claims.md
> +To ensure that authentication only succeeds if PAR is used, use [PushedAuthorizationBehavior.Require](https://source.dot.net/#Microsoft.AspNetCore.Authentication.OpenIdConnect/PushedAuthorizationBeha
```suggestion
To ensure that authentication only succeeds if PAR is used, use [PushedAuthorizationBehavior.Require](https://source.dot.net/#Microsoft.AspNetCore.Authentication.OpenIdConnect/PushedAuthorizationBehavior.cs,3af73de8f33b70c5) instead. This change also introduces a new [OnPushAuthorization](https://source.dot.net/#Microsoft.AspNetCore.Authentication.OpenIdConnect/Events/OpenIdConnectEvents.cs,6a21c8f3a90753c1) event to [OpenIdConnectEvents](/dotnet/api/microsoft.aspnetcore.authentication.openidconnect.openidconnectevents) which can be used to customize the pushed authorization request or handle it manually. See the [API proposal](https://github.com/dotnet/aspnetcore/issues/51686) for more details.
```

2024-08-16 07:03 UTC, damienbod commented on aspnetcore/security/authentication/claims.md
> +To ensure that authentication only succeeds if PAR is used, use [PushedAuthorizationBehavior.Require](https://source.dot.net/#Microsoft.AspNetCore.Authentication.OpenIdConnect/PushedAuthorizationBeha
fixed, thanks for the feedback

2024-08-16 17:01 UTC, merged