Q&M: Fix broken links identified by the Broken links report - fix aspnetcore.docs repo
dotnet/AspNetCore.Docs pull request #34001
Opened 2024-11-04 22:31 UTC by Daidihuang

2024-11-05 11:34 UTC, guardrex commented
The Blazor link changes require a few updates. I'll get to it *ASAP* 🏃‍♂️.

2024-11-05 15:39 UTC, guardrex requested changes
Thanks @Daidihuang ... I've updated the Blazor links. I'm going to go ahead and commit them now. I'll take care of that one in the progressive Blazor app article (Line 125) on that other issue that I opened.

2024-11-05 15:39 UTC, guardrex commented on aspnetcore/blazor/components/dynamiccomponent.md
> +For a working demonstration of the preceding example, see the [`DynamicComponentExample4` component in the Blazor sample app](https://github.com/dotnet/blazor-samples/blob/main/6.0/BlazorSample_Serve
```suggestion
For a working demonstration of the preceding example, see the [`DynamicComponentExample4` component in the Blazor sample app](https://github.com/dotnet/blazor-samples/blob/main/7.0/BlazorSample_Server/Pages/dynamiccomponent/DynamicComponentExample4.razor).
```

2024-11-05 15:39 UTC, guardrex commented on aspnetcore/blazor/components/layouts.md
> +* Blazor Web App `MainLayout.razor.css`
```suggestion
* [Blazor Web App `MainLayout.razor.css`](https://github.com/dotnet/aspnetcore/blob/main/src/ProjectTemplates/Web.ProjectTemplates/content/BlazorWeb-CSharp/BlazorWeb-CSharp/Components/Layout/MainLayout.razor.css)
```

2024-11-05 15:39 UTC, guardrex commented on aspnetcore/release-notes/aspnetcore-8.0.md
> +Blazor now supports the [`cancel`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/cancel_event) and [`close`](https://developer.mozilla.org/docs/Web/API/HTMLDialogElement/close_ev
No loc segments in links as long as the loc segment is redirected (added) at the destination ...

```suggestion
Blazor now supports the [`cancel`](https://developer.mozilla.org/docs/Web/API/HTMLDialogElement/cancel_event) and [`close`](https://developer.mozilla.org/docs/Web/API/HTMLDialogElement/close_event) events on the `dialog` HTML element.
```

2024-11-05 15:43 UTC, guardrex commented
BTW @Daidihuang ... Are you a vendor or a community dev? Either way, I suppose that you'll need to accept the Contributor License Agreement. Otherwise, we won't be able to merge this PR.

2024-11-05 18:10 UTC, Daidihuang commented
*   I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

     @dotnet-policy-service agree company="Microsoft"

________________________________
From: Luke Latham ***@***.***>
Sent: Tuesday, November 5, 2024 11:44 PM
To: dotnet/AspNetCore.Docs ***@***.***>
Cc: Dai di Huang (BEYONDSOFT CONSULTING INC) ***@***.***>; Mention ***@***.***>
Subject: Re: [dotnet/AspNetCore.Docs] Q&M: Fix broken links identified by the Broken links report - fix aspnetcore.docs repo (PR #34001)


BTW @Daidihuang<https://github.com/Daidihuang> ... Are you a vendor or a community dev? Either way, I suppose that you'll need to accept the Contributor License Agreement. Otherwise, we won't be able to merge this PR.

—
Reply to this email directly, view it on GitHub<https://github.com/dotnet/AspNetCore.Docs/pull/34001#issuecomment-2457516391>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BHSC3RJ5AGIUETKHPWWZCG3Z7DRVBAVCNFSM6AAAAABRFHYFEOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINJXGUYTMMZZGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-11-05 18:17 UTC, Daidihuang commented
I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@dotnet-policy-service agree company="Microsoft"




Thanks

Daidi Huang

C+E Skilling - Pubdesk - Beyondsoft Team

Team Email: ***@***.******@***.***> | Service Hour: 8:00 – 17:00 PST

C+E Skilling Publishing Desk Service<https://review.docs.microsoft.com/en-us/content-production-service/topics/pubdesk-documentation/pubdesk-internal/?branch=main>

________________________________
From: dotnet-policy-service[bot] ***@***.***>
Sent: Tuesday, November 5, 2024 11:44 PM
To: dotnet/AspNetCore.Docs ***@***.***>
Cc: Dai di Huang (BEYONDSOFT CONSULTING INC) ***@***.***>; Mention ***@***.***>
Subject: Re: [dotnet/AspNetCore.Docs] Q&M: Fix broken links identified by the Broken links report - fix aspnetcore.docs repo (PR #34001)


@Daidihuang<https://github.com/Daidihuang> please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

@dotnet-policy-service agree [company="{your company}"]


Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@dotnet-policy-service agree


  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@dotnet-policy-service agree company="Microsoft"


Contributor License Agreement
Contribution License Agreement

This Contribution License Agreement ( “Agreement” ) is agreed to by the party signing below ( “You” ),
and conveys certain license rights to the .NET Foundation ( “.NET Foundation” ) for Your contributions to
.NET Foundation open source projects. This Agreement is effective as of the latest signature date below.

1. Definitions.

“Code” means the computer software code, whether in human-readable or machine-executable form,
that is delivered by You to .NET Foundation under this Agreement.

“Project” means any of the projects owned or managed by .NET Foundation and offered under a license
approved by the Open Source Initiative (www.opensource.org<http://www.opensource.org/>).

“Submit” is the act of uploading, submitting, transmitting, or distributing code or other content to any
Project, including but not limited to communication on electronic mailing lists, source code control
systems, and issue tracking systems that are managed by, or on behalf of, the Project for the purpose of
discussing and improving that Project, but excluding communication that is conspicuously marked or
otherwise designated in writing by You as “Not a Submission.”

“Submission” means the Code and any other copyrightable material Submitted by You, including any
associated comments and documentation.

2. Your Submission. You must agree to the terms of this Agreement before making a Submission to any
Project. This Agreement covers any and all Submissions that You, now or in the future (except as
described in Section 4 below), Submit to any Project.

3. Originality of Work. You represent that each of Your Submissions is entirely Your
original work. Should You wish to Submit materials that are not Your original work,
You may Submit them separately to the Project if You (a) retain all copyright and
license information that was in the materials as you received them, (b) in the
description accompanying your Submission, include the phrase "Submission
containing materials of a third party:" followed by the names of the third party and any
licenses or other restrictions of which You are aware, and (c) follow any other
instructions in the Project's written guidelines concerning Submissions.

4. Your Employer. References to “employer” in this Agreement include Your employer or anyone else
for whom You are acting in making Your Submission, e.g. as a contractor, vendor, or agent. If Your
Submission is made in the course of Your work for an employer or Your employer has intellectual
property rights in Your Submission by contract or applicable law, You must secure permission from Your
employer to make the Submission before signing this Agreement. In that case, the term “You” in this
Agreement will refer to You and the employer collectively. If You change employers in the future and
desire to Submit additional Submissions for the new employer, then You agree to sign a new Agreement
and secure permission from the new employer before Submitting those Submissions.

5. Licenses.

a. Copyright License. You grant .NET Foundation, and those who receive the Submission directly
or indirectly from .NET Foundation, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable
license in the Submission to reproduce, prepare derivative works of, publicly display, publicly perform,
and distribute the Submission and such derivative works, and to sublicense any or all of the foregoing
rights to third parties.

b. Patent License. You grant .NET Foundation, and those who receive the Submission directly or
indirectly from .NET Foundation, a perpetual, worldwide, non-exclusive, royalty-free, irrevocable license
under Your patent claims that are necessarily infringed by the Submission or the combination of the
Submission with the Project to which it was Submitted to make, have made, use, offer to sell, sell and
import or otherwise dispose of the Submission alone or with the Project.

c. Other Rights Reserved. Each party reserves all rights not expressly granted in this Agreement.
No additional licenses or rights whatsoever (including, without limitation, any implied licenses) are
granted by implication, exhaustion, estoppel or otherwise.

6. Representations and Warranties. You represent that You are legally entitled to grant the above
licenses. You represent that each of Your Submissions is entirely Your original work (except as You may
have disclosed under Section 3 ). You represent that You have secured permission from Your employer to
make the Submission in cases where Your Submission is made in the course of Your work for Your
employer or Your employer has intellectual property rights in Your Submission by contract or applicable
law. If You are signing this Agreement on behalf of Your employer, You represent and warrant that You
have the necessary authority to bind the listed employer to the obligations contained in this Agreement.
You are not expected to provide support for Your Submission, unless You choose to do so. UNLESS
REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, AND EXCEPT FOR THE WARRANTIES
EXPRESSLY STATED IN SECTIONS 3, 4, AND 6 , THE SUBMISSION PROVIDED UNDER THIS AGREEMENT IS
PROVIDED WITHOUT WARRANTY OF ANY KIND, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTY OF
NONINFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.

7. Notice to .NET Foundation. You agree to notify .NET Foundation in writing of any facts or
circumstances of which You later become aware that would make Your representations in this
Agreement inaccurate in any respect.

8. Information about Submissions. You agree that contributions to Projects and information about
contributions may be maintained indefinitely and disclosed publicly, including Your name and other
information that You submit with Your Submission.

9. Governing Law/Jurisdiction. This Agreement is governed by the laws of the State of Washington, and
the parties consent to exclusive jurisdiction and venue in the federal courts sitting in King County,
Washington, unless  [...]

2024-11-05 20:11 UTC, guardrex approved these changes
@Rick-Anderson ... I think this is fine now. I'll work on the one more-complicated Blazor link as soon as my Internet is back up. I'll leave this to u for a final check and merge.

2024-11-06 15:11 UTC, guardrex commented
@Rick-Anderson ... I'll go ahead with this to unblock the other issue that I opened.

2024-11-06 15:22 UTC, guardrex commented on aspnetcore/test/dev-tunnels.md
> +* [Call Automation - Appointment Reminder Sample](https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/tree/kagbakpem-patch-2/CallAutomation_AppointmentReminder/CallAutomation_A
```suggestion
* [ACS Call Automation and Azure OpenAI Service](https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/tree/main/callautomation-openai-sample-csharp#acs-call-automation-and-azure-openai-service)

2024-11-06 15:31 UTC, merged