Configure JWT bearer authentication in ASP.NET Core
dotnet/AspNetCore.Docs pull request #34310
Opened 2024-12-08 14:54 UTC by damienbod

fixes https://github.com/dotnet/AspNetCore.Docs/issues/33877

@halter73 @Rick-Anderson @guardrex @mikekistler @jennyf19 @kevinchalet

2025-01-08 03:52 UTC, Rick-Anderson requested changes
Carefully review my suggestions to make sure they didn't change the meaning. After this merges and goes live, you can easily review all the links I added and suggest better links. Once you accept some of my suggestions, I can provide you a build to see how it looks built and test the links.

I'll try to finish the edit tomorrow. Really great stuff here our customers will welcome.

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Access tokens are intended solely for making requests to an API. This is normally sent to the API in the **Authorization** request header as a bearer token.
```suggestion
Access tokens:

* Are strings used by a client app to make requests to the server implementing an API.
* Can vary in format. Different APIs may use different formats for the tokens.
* Can be encrypted.
* Should never be read or interpreted by a web client or UI app holding the access token.
* Are intended solely for making requests to an API.
* Are typically sent to the API in the **Authorization** request header as a bearer token.
```

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +#### Application access tokens and delegeted Access tokens
```suggestion
#### Application access tokens and delegated access tokens
```

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +When requesting or creating an access token, an application or an application acting on behalf of a user can request an access token. The tokens are **application access tokens** or **delegated acces
```suggestion
When requesting or creating an access token, an app, or an app acting on behalf of a user, can request an access token. These tokens can be either *application access tokens* or *delegated access tokens*. The tokens have different claims and are managed and stored differently. An *application access token* is typically stored once in the app until it expires, while a *delegated access token* is stored per user, either in a cookie or in a secure server cache.
```

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +It is recommended to use delegated user access tokens whenever a user is involved. Downstream APIs can request a delegated user access token on behalf of the authenticated user.
```suggestion
We recommend using delegated user access tokens whenever a user is involved. Downstream APIs can request a delegated user access token on behalf of the authenticated user. 
```

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +- MTLS
```suggestion
There are two types of access tokens: [bearer tokens](https://cloud.google.com/docs/authentication/token-types#bearer) and [sender-constrained tokens](https://docs.verify.ibm.com/ibm-security-verify-access/docs/tasks-certboundaccesstoken). Sender-constrained tokens require the requesting client to prove possession of a private key to use the token. Proving possession of a private key guarantees the token can't be used independently. Sender-constrained tokens can be implemented in two ways:

- [Demonstrating Proof-of-Possession (DPoP)](https://curity.io/resources/learn/dpop-overview)
- [Mutual TLS (MTLS)](https://www.securew2.com/blog/mutual-tls-mtls-authentication)
```

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +ID tokens are security tokens that confirm a user’s successful authentication. The tokens allow the client to verify the user’s identity. The secure token server issues ID tokens containing claims wi
I deleted secure from secure token server. Aren't JWT servers secure? Per MS style guide, less is more.

```suggestion
ID tokens are security tokens that confirm a user’s successful authentication. The tokens allow the client to verify the user’s identity. The JWT token server issues ID tokens containing claims with user information. ID tokens are always in [JWT](https://jwt.io/introduction) format.
```

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +ID tokens should never be used to access APIs.
```suggestion
ID tokens ***should never*** be used to access APIs.
```

2025-01-08 03:52 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +There are many different types of tokens as well as access tokens and ID tokens. OpenID Connect and OAuth standards specify many different types. Refresh tokens can be used to refresh a UI applicatio
```suggestion
There are many types of tokens, including access and ID tokens, as specified by OpenID Connect and OAuth standards. Refresh tokens can be used to refresh a UI app without re-authenticating the user. [OAuth JAR tokens](https://connect2id.com/products/nimbus-oauth-openid-connect-sdk/examples/oauth/jar) can securely send authorization requests. Verifiable credentials flows utilize JWT types for issuing or verifying credentials. It is crucial to use tokens according to the specifications. See the standards links provided later in this article for more information.
```

2025-01-08 10:47 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +There are many different types of tokens and many formats. You should not be creating access tokens or ID tokens yourself unless in testing scenarios. Creating self-made tokens and not following stan
Fixed in commit: Fix Token types 

I used different links and did not specify the OAuth link, because there are multiple standards defined for this.

2025-01-08 10:52 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +#### Application access tokens and delegeted Access tokens
fixed

2025-01-08 10:59 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +When requesting or creating an access token, an application or an application acting on behalf of a user can request an access token. The tokens are **application access tokens** or **delegated acces
fixed

2025-01-08 11:00 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +It is recommended to use delegated user access tokens whenever a user is involved. Downstream APIs can request a delegated user access token on behalf of the authenticated user.
fixed

2025-01-08 12:40 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +ID tokens are security tokens that confirm a user’s successful authentication. The tokens allow the client to verify the user’s identity. The secure token server issues ID tokens containing claims wi
fixed

2025-01-08 12:41 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +ID tokens should never be used to access APIs.
fixed

2025-01-08 12:46 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +There are many different types of tokens as well as access tokens and ID tokens. OpenID Connect and OAuth standards specify many different types. Refresh tokens can be used to refresh a UI applicatio
fixed

2025-01-09 03:21 UTC, Rick-Anderson requested changes
I'll try to finish tomorrow. Double check because I may have changed the meaning.

2025-01-09 03:21 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +When using access tokens, only the access token is validated on the API. The process of acquiring the access token is unspecified.  OpenID Connect and OAuth specify standards on how to acquire access
```suggestion
When an API uses JWT access tokens for authorization, the API only validates the access token, not on how the token was obtained.

OpenID Connect (OIDC) and OAuth 2.0 provide standardized, secure frameworks for token acquisition. Token acquisition varies depending on the type of app. Due to the complexity of secure token acquisition, it's highly recommended to rely on these standards:

* For apps acting on behalf of a user: OIDC is the preferred choice, enabling delegated user access. In web apps, the confidential code flow with [Proof Key for Code Exchange](https://oauth.net/2/pkce/) (PKCE) is recommended for enhanced security.
* If the app has no user: The OAuth 2.0 client credentials flow is suitable for obtaining application access tokens.
```

2025-01-09 19:47 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Bearer tokens are often treated as an authentication mechanism, but in practice, they used primarily for authorization. Authentication occurs when a user first requests an access token in the UI laye
Fixed

2025-01-09 19:51 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +When using JWT access tokens to authorize an API, the request is allowed, or not allowed. If the request is not authorized, a 401 response or a 403 response is returned. The API should never redirect
fixed

2025-01-09 19:57 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +A 401 response is returned when the access token has an invalid standard requirement. The OAuth specifications are clear which claims must be valid and how to validate the claims in the access token.
fixed

2025-01-09 20:03 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +When using access tokens, only the access token is validated on the API. The process of acquiring the access token is unspecified.  OpenID Connect and OAuth specify standards on how to acquire access
Fixed

2025-01-09 20:03 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +## How OIDC/OAuth fits into this?
Updated to ## What role has OIDC and/or OAuth when using bearer tokens?

2025-01-09 20:06 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +A 403 forbidden response is normally returned when a business permission is missing. The authorization has nothing to do with the authentication or the standard claims used in the access token. This
fixed

2025-01-09 22:33 UTC, Rick-Anderson reviewed
Any reason you don't push, then add to batch the suggestions you agree with?
<img width="103" alt="image" src="https://github.com/user-attachments/assets/52bcfe77-4aab-4f1d-815e-af710f64537f" />

2025-01-10 02:34 UTC, Rick-Anderson requested changes
Wow, what an amazing doc. This is going to be super helpful to customers.

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +> If deploying the production, the cache should work in a mutli-instance deployment and a persistent cache is normally required.
```suggestion
> If deploying to production, the cache should work in a mutli-instance deployment. A persistent cache is normally required.
```

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +YARP (Yet Another Reverse Proxy) is a great tool for handling http requests and forwarding the requests to other APIs. YARP can implement security logic for acquiring new access credentials. YARP is
```suggestion
[YARP (Yet Another Reverse Proxy)](https://microsoft.github.io/reverse-proxy/) is a good tool for handling HTTP requests and forwarding the requests to other APIs. YARP can implement security logic for acquiring new access credentials. YARP is frequently used in the [backend for frontend (BFF)](https://auth0.com/blog/the-backend-for-frontend-pattern-bff/) security architecture.
```

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Testing secure APIs can be implemented in different ways. Integration tests and containers with access tokens can be used to test the APIs. You can also create the access tokens using the dotnet user
```suggestion
Integration tests and containers with access tokens can be used to test secure APIs. Access tokens can be created using the [dotnet user-jwts tool](/aspnet/core/security/authentication/jwt-authn).
```

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +[Manage JSON Web Tokens in development with dotnet user-jwts](xref:security/authentication/jwt)
```suggestion
```

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +It is important not to create security problems in the API so that you can test the API. When delegated access tokens are used, it is more difficult to test as the tokens can only be created using a
```suggestion
Ensure that security problems are **not** introduced into the API for testing purposes. Testing becomes more challenging when delegated access tokens are used, as these tokens can only be created through a UI and an OpenID Connect flow. If a test tool is used to create delegated access tokens, security features must be disabled for testing. It's essential that these features are only disabled in the test environment.

Create dedicated and isolated test environments where security features can safely be disable or modified. Ensure these changes are strictly limited to the test environment.
```

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Swagger and Postman are great UI tools for testing APIs. For the tools to work, the API can produce an Open API document and this can be loaded into the client testing tool. A security flow to acquir
Rewrite this without Postman. PM has been nixed by MS security.  We replace PM with Curl.

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +> Note
```suggestion
> Warning
```

2025-01-10 02:34 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +If implementing a Swagger UI for an API, you should normally not deploy the UI to production as the security must be weakened to allow this to work.
```suggestion
Swagger UI for an API should only be enabled in the development environment, and never in production. Security must be lowered to enable Swagger UI .
```

Or, weaker version, less secure version

```suggestion
When implementing a Swagger UI for an API, you should normally not deploy the UI to production as the security must

folks who limit and control  access to the production app know they can skip this mandate.

2025-01-10 06:46 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Swagger and Postman are great UI tools for testing APIs. For the tools to work, the API can produce an Open API document and this can be loaded into the client testing tool. A security flow to acquir
fixed

2025-01-10 06:55 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +If implementing a Swagger UI for an API, you should normally not deploy the UI to production as the security must be weakened to allow this to work.
fixed, sometimes the UI is required in production, with weakened security headers

2025-01-10 06:55 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +[Manage JSON Web Tokens in development with dotnet user-jwts](xref:security/authentication/jwt)
I think we need this link?

2025-01-10 23:00 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +			var jwtHandler = new JwtSecurityTokenHandler();
Can we update this to use the `JsonWebTokenHandler`? It's faster and what's now used by default internally by the JWT and OIDC auth handers.

2025-01-10 23:01 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +				}
```suggestion
				if (issuer == Consts.MY_THIRD_PARTY_ISS) // Third party identity provider
				{
					return Consts.MY_THIRD_PARTY_SCHEME;
				}
```

2025-01-10 23:04 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication/sample/JwtBearer/Program.cs
> +            });
```suggestion
```

It doesn't look like "some-scheme" is referenced anywhere.

2025-01-10 23:07 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication/sample/JwtBearer/Program.cs
> +            .SetFallbackPolicy(requireAuthPolicy);
```suggestion
```

We already using `MapControllers().RequireAuthorization()` and `[Authorize]`. It's worth documenting how to set a fallback policy which we already do above, but I don't think we need it in the main sample. I have seen it cause too many issues with Blazor and `[AllowAnonymous]` on specific pages because the fallback policy still gets applied to the static Blazor JS resources.

2025-01-10 23:07 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication/sample/JwtBearer/Program.cs
> +            .RequireAuthorization();
```suggestion
        app.MapControllers();
```

I think using the `[Authorize]` attribute on the one controller should be sufficient.

2025-01-10 23:23 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Testing secure APIs can be implemented in different ways. Integration tests and containers with access tokens can be used to test the APIs. You can also create the access tokens using the dotnet user
@damienbod @halter73  I fixed the link and moved it to where it's used. It reads better and the MS style guide mantra is less is more.

<img width="339" alt="image" src="https://github.com/user-attachments/assets/02712651-85d5-4518-915b-b9082baba0d7" />

2025-01-11 07:48 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +You should NOT create an access token from a username/password request. This is not authentication and is open to impersonation attacks and phishing attacks. Access tokens should only be created usin
fixed

2025-01-11 07:50 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Secure web applications require a backend and store access tokens somewhere on the trusted server. Only a secure HTTP only cookie is shared on the client browser.
fixed

2025-01-11 07:55 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +APIs sometimes require user data from downstream APIs on behalf of the user authenticated in the calling application. The API could just implement an OAuth client credentials flow, but this would mea
fixed

2025-01-11 08:01 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +This works very well and is super easy to implement when using Microsoft .Identity.Web. It only works with Microsoft Entra ID, Microsoft Entra External ID and Microsoft Azure AD B2C.
Fixed: Using the [Microsoft Identity Web authentication library](/entra/msal/dotnet/microsoft-identity-web/) is the easiest and a secure approach. It only works with Microsoft Entra ID, Microsoft Entra External ID.

2025-01-11 08:03 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +See [[Microsoft identity platform and OAuth 2.0 On-Behalf-Of flow](/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)
fixed

2025-01-11 08:11 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +Duende.AccessTokenManagement.OpenIdConnect is a great Nuget package for handling and managing access tokens in the client application.
Fixed, used the link to the FOSS part

2025-01-11 08:18 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +* Testing APIs
removed

2025-01-11 08:22 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +	jwtOptions.Authority = builder.Configuration["Api:Authority"];
The authority is also used for validation of a claim in the access token returned in some client libraries.

2025-01-11 08:31 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +		ValidAudiences = builder.Configuration.GetSection("Api:ValidAudiences").Get<string[]>(),
Updated this with some text. I have encountered every combination of the setup depending on the access token and the secure token server and the client library used for validation.

2025-01-11 08:31 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +		ValidAudiences = builder.Configuration.GetSection("Api:ValidAudiences").Get<string[]>(),
@halter73 Update good? Or change?

2025-01-11 08:49 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +> If deploying the production, the cache should work in a mutli-instance deployment and a persistent cache is normally required.
fixed

2025-01-11 08:57 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +})
fixed

2025-01-11 09:06 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +			var jwtHandler = new JwtSecurityTokenHandler();
Updated to JsonWebTokenHandler

2025-01-11 09:07 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +			var jwtHandler = new JwtSecurityTokenHandler();
And ReadJsonWebToken

2025-01-11 09:09 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +	jwtOptions.MapInboundClaims = false;
Added a link

2025-01-11 09:13 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +### JWT with multiple schemes
@halter73 @Rick-Anderson  new PR?

2025-01-11 11:26 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +### JWT with multiple schemes
fixed

2025-01-11 16:00 UTC, mikekistler reviewed
I left a few comments. I will try out the example code and may have more after that.

2025-01-11 16:51 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
Added

2025-01-11 16:53 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +When using JWT access tokens for API authorization, the API grants or denies access based on the provided token. If the request is not authorized, a 401 or 403 response is returned. The API shouldn't
added

2025-01-11 20:38 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +```
fixed

2025-01-13 19:39 UTC, Rick-Anderson approved these changes

2025-01-13 20:05 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
How about an intro?

```suggestion

JWT (JSON Web Token) Bearer Authentication bearer authentication is commonly utilized for APIs. While it operates similarly to cookie authentication, instead of a cookie, the server issues a JWT upon successful authentication. This JWT is a self-contained token that encapsulates user information and permissions. The client then includes the JWT in the Authorization header for all subsequent requests.
```

2025-01-13 21:06 UTC, damienbod commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
Fixed with this:

JWT (JSON Web Token) Bearer Authentication is commonly utilized for APIs. While it operates similarly to cookie authentication, instead of a cookie, the server issues a JWT or tokens upon a successful authentication. A JWT is a self-contained token that encapsulates information for an API resource or a client. The client which requested the JWT can request data from an API resource using the Authorization header and a bearer token.

2025-01-13 21:17 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
Massive improvement o my version and I think makes for a great intro.

2025-01-16 23:49 UTC, halter73 approved these changes
Thank you!

2025-01-16 23:49 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +JWT (JSON Web Token) Bearer Authentication is commonly utilized for APIs. While it operates similarly to cookie authentication, instead of a cookie, the server issues a JWT or tokens upon a successfu
```suggestion
JWT (JSON Web Token) Bearer Authentication is commonly utilized for APIs. While it operates similarly to cookie authentication, instead of a cookie, the identity provider issues a JWT or tokens upon a successful authentication. A JWT is a self-contained token that encapsulates information for an API resource or a client. The client which requested the JWT can request data from an API resource using the Authorization header and a bearer token.
```

I don't want to imply that the server running ASP.NET Core has built-in support to issue JWTs.

2025-01-16 23:49 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
```suggestion
```

I should have asked for this earlier, but can we remove this section? I don't know who this helps. To me it only seems to muddy the waters. Bearer tokens are a critical to authentication when you're using the `JwtBearerHandler`, but in the end it's just a trusted bag of claims much like a cookie.

It sounds like you're trying to convey that, unlike with cookies, it's okay for a web application to forward JWT access tokens to other services, but that's already well covered in the "Downstream APIs" section. I don't think this should be the first section after the intro. It makes far more sense to lead with "Token Types".

2025-01-17 21:29 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
@halter73  to me, without an intro, it's muddy waters

For someone new to JWT, I think it's helpful to point out at the top, it's more than authentication .

Per @halter73 

 comment https://github.com/dotnet/AspNetCore.Docs/pull/34310#discussion_r1919377225, 

 > but that's already well covered in the "Downstream APIs" section.

 I think it's OK to provide introductory concepts when they are covered later in the doc.
 
 Can we add something like the following?



```suggestion

* **Authentication**: When using the `JwtBearerHandler`, bearer tokens are essential for authentication. The `JwtBearerHandler` validates the token and extracts the user's identity from its claims.
* **Authorization**: Bearer tokens enable authorization by providing a collection of claims representing the user's permissions, much like a cookie.
* **Delegated Authorization**: When a token is presented to an API, this process is known as *delegated authorization*. The API uses the claims within the token to determine if the user is authorized to access the requested endpoint.
* **Token Transparency**: The token doesn't reveal who or what obtained it, or how it was issued.

```

2025-01-17 21:39 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
```suggestion

For an introduction to JWT Bearer Authentication, see [JSON Web Tokens](https://jwt.io/introduction/.)
```

2025-01-17 22:01 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
@halter73  to me, without an intro, it's muddy waters

For someone new to JWT, I think it's helpful to point out at the top, it's more than authentication .

Per @halter73 

 comment https://github.com/dotnet/AspNetCore.Docs/pull/34310#discussion_r1919377225, 

 > but that's already well covered in the "Downstream APIs" section.

 I think it's OK to provide introductory concepts when they are covered later in the doc.
 
 Can we add something like the following?

The suggestion seems better in the introduction, it doesn't seem to fit in token types. Maybe move it back

```suggestion

JWT Bearer Authentication provides:

* **Authentication**: When using the `JwtBearerHandler`, bearer tokens are essential for authentication. The `JwtBearerHandler` validates the token and extracts the user's identity from its claims.
* **Authorization**: Bearer tokens enable authorization by providing a collection of claims representing the user's permissions, much like a cookie.
* **Delegated Authorization**: When a token is presented to an API, this process is known as *delegated authorization*. The API uses the claims within the token to determine if the user is authorized to access the requested endpoint.
* **Token Transparency**: The token doesn't reveal who or what obtained it, or how it was issued.

```

2025-01-17 22:05 UTC, Rick-Anderson commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +JWT (JSON Web Token) Bearer Authentication is commonly utilized for APIs. While it operates similarly to cookie authentication, the identity provider issues a JWT or tokens upon a successful authenti
Split up RO sentence:

```suggestion
JWT (JSON Web Token) Bearer Authentication is commonly utilized for APIs. While it operates similarly to cookie authentication, the identity provider issues a JWT or tokens upon a successful authentication. These tokens can then be sent to other servers to authenticate, unlike cookies which are only sent back to the issuing domain. A JWT is a self-contained token that encapsulates information for an API resource or a client. The client which requested the JWT can request data from an API resource using the Authorization header and a bearer token.
```

2025-01-18 02:17 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
What's wrong the current intro?

> JWT (JSON Web Token) Bearer Authentication is commonly utilized for APIs. While it operates similarly to cookie authentication, the identity provider issues a JWT or tokens upon a successful authentication. These tokens can then be sent to other servers to authenticate, unlike cookies which are only sent back to the issuing domain. A JWT is a self-contained token that encapsulates information for an API resource or a client. The client which requested the JWT can request data from an API resource using the Authorization header and a bearer token.

Is it that it doesn't mention claims? Or do we want a bulleted list for easy skim reading?

```suggestion

JWT Bearer Authentication provides:

* **Authentication**: When using the `JwtBearerHandler`, bearer tokens are essential for authentication. The `JwtBearerHandler` validates the token and extracts the user's identity from its claims.
* **Authorization**: Bearer tokens enable authorization by providing a collection of claims representing the user's or application's permissions, much like a cookie.
* **Delegated Authorization**: When a user-specific access token is used to authenticate between APIs instead of an application-wide access token, this process is known as *delegated authorization*.

```

If we want a bulleted list, maybe go with this? A JWT doesn't necessarily have to reveal how it was issued, but it often does. The `iss` or issuer is a standard claim. In Entra it tells you this:

> Identifies the issuer, or "authorization server" that constructs and returns the token. It also identifies the tenant for which the user was authenticated.

https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference#payload-claims

This seems to me to indicate at least a few things about how it was issued. It's true that the token might have been forwarded, and you'd have no way to know that just by inspecting the token, but I don't think that's worth mentioning in an intro.

2025-01-18 02:34 UTC, halter73 commented on aspnetcore/security/authentication/configure-jwt-bearer-authentication.md
> +
```suggestion

For an introduction to JWT Bearer Authentication, see [JSON Web Tokens.](https://en.wikipedia.org/wiki/JSON_Web_Token)
```

It's pretty similar content, but Wikipedia is more in-depth vender neutral. I also think people new to the space will more likely be overwhelmed by mentions of HMAC, RSA and ECDSA without links in the Okta intro than the intro to the Wikipedia article which gives a good example of a "logged in as administrator" claim in the intro. The Okta only explains claims later on in the "Payload" section.

2025-01-19 02:05 UTC, merged

2025-01-19 06:51 UTC, damienbod commented
Thanks @halter73  @Rick-Anderson @mikekistler This was a big one.

Greetings Damien